CREATE TABLE [ECOMMERCE].[T_Registration] (
    [RegID]                           INT           IDENTITY (1, 1) NOT NULL,
    [CustomerID]                      VARCHAR (MAX) NOT NULL,
    [FirstName]                       VARCHAR (MAX) NOT NULL,
    [MiddleName]                      VARCHAR (MAX) NULL,
    [LastName]                        VARCHAR (MAX) NOT NULL,
    [GenderID]                        INT           NULL,
    [DateofBirth]                     DATETIME      NULL,
    [EmailID]                         VARCHAR (MAX) NULL,
    [MobileNo]                        VARCHAR (16)  NOT NULL,
    [HighestEducationQualificationID] INT           NULL,
    [Address]                         VARCHAR (MAX) NULL,
    [CityID]                          INT           NULL,
    [StateID]                         INT           NULL,
    [CountryID]                       INT           NULL,
    [Pincode]                         VARCHAR (20)  NULL,
    [StatusID]                        INT           NULL,
    [RegistrationSource]              VARCHAR (MAX) NULL,
    [CreatedOn]                       DATETIME      NULL,
    [CreatedBy]                       VARCHAR (MAX) NULL,
    [UpdatedOn]                       DATETIME      NULL,
    [UpdatedBy]                       VARCHAR (MAX) NULL,
    [Gender]                          VARCHAR (MAX) NULL,
    [HighestEducationQualification]   VARCHAR (MAX) NULL,
    [City]                            VARCHAR (MAX) NULL,
    [State]                           VARCHAR (MAX) NULL,
    [Country]                         VARCHAR (MAX) NULL,
    [GuardianName]                    VARCHAR (MAX) NULL,
    [GuardianMobileNo]                VARCHAR (MAX) NULL,
    [SecondLanguage]                  VARCHAR (MAX) NULL,
    [SocialCategory]                  VARCHAR (MAX) NULL
);

