CREATE TABLE [ERP].[T_Oracle_Push] (
    [Oracle_ENTITY_NAME]    VARCHAR (MAX) NULL,
    [COST_CENTRE_CODE]      INT           NULL,
    [TRANSACTION_TYPE_NAME] VARCHAR (MAX) NOT NULL,
    [TRANSACTION_NUMBER]    INT           NOT NULL,
    [TOTAL_AMOUNT]          NUMERIC (18)  NULL,
    [TRANSACTION_DATE]      DATETIME      NULL,
    [INSTRUMENT_NO]         VARCHAR (MAX) NULL,
    [BANK_ACCOUNT_NAME]     VARCHAR (MAX) NULL,
    [INTERFACE_FLAG]        VARCHAR (MAX) NULL,
    [Oracle_ERROR_MESSAGE]  VARCHAR (MAX) NULL
);

