CREATE PROCEDURE [EOS].[uspGetAllExamComponentOfEmployee]
(
	@iEmployeeID INT
)
AS
BEGIN

	SET NOCOUNT ON;

	SELECT DISTINCT SEM.[I_EXAM_COMPONENT_ID],[ECM].[S_COMPONENT_NAME] FROM EOS.T_EMPLOYEE_SKILL_MAP ESM WITH(NOLOCK) 
	INNER JOIN T_EMPLOYEE_DTLS ED WITH(NOLOCK) ON ESM.I_EMPLOYEE_ID=ED.I_EMPLOYEE_ID
	INNER JOIN EOS.[T_SKILL_EXAM_MAP] SEM WITH(NOLOCK) ON SEM.[I_SKILL_ID]=[ESM].[I_SKILL_ID]
	INNER JOIN [T_EXAM_COMPONENT_MASTER] ECM WITH(NOLOCK) ON [ECM].[I_EXAM_COMPONENT_ID]=[SEM].[I_EXAM_COMPONENT_ID]
	WHERE ED.[I_EMPLOYEE_ID]=@IEMPLOYEEID 

	UNION

	SELECT DISTINCT SEM.[I_EXAM_COMPONENT_ID],[ECM].[S_COMPONENT_NAME] FROM EOS.T_EMPLOYEE_ROLE_MAP TERM WITH(NOLOCK)
	INNER JOIN EOS.T_ROLE_SKILL_MAP TRSM WITH(NOLOCK) ON TERM.I_ROLE_ID = TRSM.I_ROLE_ID
	INNER JOIN T_EMPLOYEE_DTLS ED WITH(NOLOCK) ON TERM.I_EMPLOYEE_ID=ED.I_EMPLOYEE_ID
	INNER JOIN EOS.[T_SKILL_EXAM_MAP] SEM WITH(NOLOCK) ON SEM.[I_SKILL_ID]=TRSM.[I_SKILL_ID]
	INNER JOIN [T_EXAM_COMPONENT_MASTER] ECM WITH(NOLOCK) ON [ECM].[I_EXAM_COMPONENT_ID]=[SEM].[I_EXAM_COMPONENT_ID]
	WHERE TERM.I_EMPLOYEE_ID =@IEMPLOYEEID AND TRSM.[I_BRAND_ID] IN
	( 
		SELECT [I_BRAND_ID] FROM  [T_BRAND_CENTER_DETAILS] WHERE [I_CENTRE_ID] IN 
		(
			SELECT [I_CENTRE_ID] FROM [T_EMPLOYEE_DTLS] WHERE [I_EMPLOYEE_ID]=@IEMPLOYEEID
		)
	)
	AND  TRSM.[I_CENTRE_ID] IS NULL OPTION (MAXDOP 1)

END
