CREATE FUNCTION [dbo].[Func_KPMG_InstallmentStatus] 
(
	
	@InvoiceChildDetailId INT
	
)
RETURNS CHAR(1)
AS
BEGIN
	DECLARE @IS_INSTALLMENT_PAID CHAR(1)
	SET @IS_INSTALLMENT_PAID ='N'
	DECLARE @AMOUNT_DUE DECIMAL(18,2)
	DECLARE @AMOUNT_PAID DECIMAL(18,2)
	SELECT @AMOUNT_DUE=SUM( N_Amount_Due) FROM T_INVOICE_CHILD_DETAIL WHERE I_Invoice_Detail_ID=@InvoiceChildDetailId
	SELECT @AMOUNT_PAID =SUM(N_Amount_Paid) FROM T_RECEIPT_COMPONENT_DETAIL A
	INNER JOIN T_RECEIPT_HEADER B ON A.I_Receipt_Detail_ID=B.I_Receipt_Header_ID
	AND I_Invoice_Detail_ID=@InvoiceChildDetailId
	IF((@AMOUNT_DUE-@AMOUNT_PAID)<=1)
	BEGIN
		SET @IS_INSTALLMENT_PAID='Y'
	END
	ELSE
	BEGIN
		SET @IS_INSTALLMENT_PAID='N'
	END
	


	RETURN @IS_INSTALLMENT_PAID
		 
END