
CREATE FUNCTION VALUE_SPLITING
(
  @LIST NVARCHAR(2000),
  @SPLIT NVARCHAR(10)
)
RETURNS @RETURN TABLE
(
  ID INT IDENTITY (1,1),
  Value NVARCHAR(100)
)
AS
BEGIN 
WHILE (CHARINDEX(@SPLIT,@LIST)>0)
BEGIN 
INSERT INTO @RETURN(VALUE)
SELECT 
Value = ltrim(rtrim(SUBSTRING(@LIST,1,CHARINDEX(@SPLIT,@LIST)-1)))
SET @LIST=SUBSTRING(@LIST,CHARINDEX(@SPLIT,@LIST)+LEN(@SPLIT),LEN(@LIST))
END
INSERT INTO @RETURN(Value)
SELECT VALUE_SPLITING=LTRIM(rtrim(@LIST))
RETURN
END