CREATE PROCEDURE [ERP].[uspGetBankListFromERP]
(
	@iBrandID INT
)
AS
BEGIN

CREATE TABLE #temp
(
BANK_ACCOUNT_NAME VARCHAR(MAX),
BANK_ACCOUNT_NUM VARCHAR(MAX),
ENTITY_NAME VARCHAR(MAX),
BRAND_ID INT
)

INSERT INTO #temp
        ( BANK_ACCOUNT_NAME ,
          BANK_ACCOUNT_NUM ,
          ENTITY_NAME
        )
	SELECT * FROM BANK_ACCOUNTS ERPBank
	--INNER JOIN dbo.T_Brand_Master TBM ON TBM.S_Brand_Code = ERPBank.Entity_Name
	--WHERE I_Brand_ID = ISNULL(@iBrandID, I_Brand_ID)
	
	UPDATE #temp SET BRAND_ID=107 WHERE ENTITY_NAME LIKE '%AIS%'
	UPDATE #temp SET BRAND_ID=108 WHERE ENTITY_NAME LIKE '%AIT %'
	UPDATE #temp SET BRAND_ID=109 WHERE ENTITY_NAME LIKE '%RICE%'
	UPDATE #temp SET BRAND_ID=110 WHERE ENTITY_NAME LIKE '%AWS%'
	UPDATE #temp SET BRAND_ID=111 WHERE ENTITY_NAME LIKE '%Adamas Career%'
	UPDATE #temp SET BRAND_ID=112 WHERE ENTITY_NAME LIKE '%AHSMS%'
	
	SELECT BANK_ACCOUNT_NAME,BANK_ACCOUNT_NUM,ENTITY_NAME FROM #temp T WHERE BRAND_ID=@iBrandID;
END
