CREATE PROCEDURE [dbo].[DeleteEmp]

as
begin


DROP TABLE #TEMPUSER

SELECT I_USER_ID, I_REFERENCE_ID INTO #TEMPUSER
FROM T_USER_MASTER
WHERE I_USER_ID >=545 AND I_USER_ID<=559

DELETE FROM T_USER_HIERARCHY_DETAILS
WHERE I_USER_ID IN (SELECT I_USER_ID FROM #TEMPUSER )

DELETE FROM T_USER_ROLE_DETAILS
WHERE I_USER_ID IN (SELECT I_USER_ID FROM #TEMPUSER )

DELETE FROM T_USER_MASTER
WHERE I_USER_ID IN (SELECT I_USER_ID FROM #TEMPUSER )


DELETE FROM EOS.T_EMPLOYEE_ADDRESS
WHERE I_EMPLOYEE_ID IN (SELECT I_REFERENCE_ID FROM #TEMPUSER )

DELETE FROM EOS.T_EMPLOYEE_SKILL_MAP
WHERE I_EMPLOYEE_ID IN (SELECT I_REFERENCE_ID FROM #TEMPUSER )

DELETE FROM EOS.T_EMPLOYEE_ROLE_MAP
WHERE I_EMPLOYEE_ID IN (SELECT I_REFERENCE_ID FROM #TEMPUSER )

DELETE FROM EOS.T_EMPLOYEE_QUALIFICATION
WHERE I_EMPLOYEE_ID IN (SELECT I_REFERENCE_ID FROM #TEMPUSER )

DELETE FROM EOS.T_EMPLOYEE_WORKEXP
WHERE I_EMPLOYEE_ID IN (SELECT I_REFERENCE_ID FROM #TEMPUSER )

DELETE FROM T_EMPLOYEE_DTLS
WHERE I_EMPLOYEE_ID IN (SELECT I_REFERENCE_ID FROM #TEMPUSER )

end
