CREATE PROCEDURE [REPORT].[AptechuspGetEnquiryEnrollmentReportDetails]
(
	@SHIERARCHYLIST VARCHAR(MAX),
	@IBRANDID INT,
	@DTSTARTDATE DATETIME,
	@DTENDDATE DATETIME
)
AS
BEGIN TRY


DECLARE @EEBCINITIAL TABLE
(
	I_CENTRE_ID INT,
	CENTERCODE VARCHAR(20),
	CENTERNAME VARCHAR(100),
	INSTANCECHAIN VARCHAR(200),
	S_CURRENCY_CODE VARCHAR(50)
)

DECLARE @EEBCANALYSIS TABLE
(
	I_CENTRE_ID INT,
	CENTERCODE VARCHAR(20),
	CENTERNAME VARCHAR(100),
	INSTANCECHAIN VARCHAR(200),
	S_CURRENCY_CODE VARCHAR(50),
	MONTH INT,
	YEAR INT,
	TOTAL_ENQUIRY INT,
	TOTAL_ENROLL INT,
	INVOICE_AMOUNT NUMERIC(18,2),
	COLLECTION_AMOUNT NUMERIC(18,2),
	NoLastReceipt VarChar(50),
	DtLastReceipt DateTime,
	NoLastInvoice VarChar(50),
	DtLastInvoice DateTime
)
DECLARE @YEARMONTH TABLE
(
	MONTH INT,
	YEAR INT
)

DECLARE @MONTH_START INT
DECLARE @MONTH_CURRENT INT
DECLARE @MONTH_END INT
DECLARE @YR_START INT
DECLARE @YR_CURRENT INT
DECLARE @YR_END INT

DECLARE @TOTAL_ENQUIRY INT
DECLARE @TOTAL_ENROLL INT
DECLARE @INVOICE_AMOUNT NUMERIC(18,2)
DECLARE @COLLECTION_AMOUNT NUMERIC(18,2)

DECLARE @CENTERID INT
DECLARE @CENTERCODE VARCHAR(20)
DECLARE @CENTERNAME VARCHAR(100)
DECLARE @INSTANCECHAIN VARCHAR(200)
DECLARE @CURRENCYCODE VARCHAR(50)

SELECT @MONTH_START=MONTH(@DTSTARTDATE)
SELECT @MONTH_CURRENT=MONTH(@DTSTARTDATE)
SELECT @MONTH_END=MONTH(@DTENDDATE)
SELECT @YR_START=YEAR(@DTSTARTDATE)
SELECT @YR_CURRENT=YEAR(@DTSTARTDATE)
SELECT @YR_END=YEAR(@DTENDDATE)

INSERT INTO @EEBCINITIAL
SELECT DISTINCT 
FN1.CENTERID,
FN1.CENTERCODE,
FN1.CENTERNAME,
FN2.INSTANCECHAIN,
CUM.S_CURRENCY_CODE
FROM [DBO].[FNGETCENTERSFORREPORTS](@SHIERARCHYLIST, @IBRANDID) FN1
INNER JOIN [DBO].[FNGETINSTANCENAMECHAINFORREPORTS](@SHIERARCHYLIST, @IBRANDID) FN2 ON FN1.HIERARCHYDETAILID=FN2.HIERARCHYDETAILID
INNER JOIN DBO.T_CENTRE_MASTER CEM WITH(NOLOCK) ON FN1.CENTERID=CEM.I_CENTRE_ID
INNER JOIN DBO.T_COUNTRY_MASTER COM WITH(NOLOCK) ON CEM.I_COUNTRY_ID=COM.I_COUNTRY_ID
INNER JOIN DBO.T_CURRENCY_MASTER CUM WITH(NOLOCK) ON COM.I_CURRENCY_ID=CUM.I_CURRENCY_ID
ORDER BY CENTERID


WHILE (@YR_END>@YR_CURRENT) OR (@YR_END=@YR_CURRENT AND @MONTH_END>=@MONTH_CURRENT)
BEGIN
	INSERT INTO @YEARMONTH VALUES(@MONTH_CURRENT,@YR_CURRENT)
	IF @MONTH_CURRENT =12
		BEGIN
			SELECT @MONTH_CURRENT = 1
			SELECT @YR_CURRENT=@YR_CURRENT+1
		END
	ELSE
		BEGIN
			SELECT @MONTH_CURRENT = @MONTH_CURRENT +1
		END
END

INSERT INTO @EEBCANALYSIS (I_CENTRE_ID,CENTERCODE,CENTERNAME,INSTANCECHAIN,S_CURRENCY_CODE,MONTH,YEAR)
(
SELECT DISTINCT
A.I_CENTRE_ID, 
A.CENTERCODE, 
A.CENTERNAME,
A.INSTANCECHAIN,
A.S_CURRENCY_CODE,
B.MONTH,
B.YEAR
FROM DBO.T_ENQUIRY_REGN_DETAIL C WITH(NOLOCK) 
INNER JOIN @EEBCINITIAL A ON A.I_CENTRE_ID=C.I_CENTRE_ID
INNER JOIN @YEARMONTH B ON MONTH(C.DT_CRTD_ON)=B.MONTH
AND YEAR(C.DT_CRTD_ON)=B.YEAR WHERE C.I_ENQUIRY_STATUS_CODE<>0 

UNION 

SELECT DISTINCT
A.I_CENTRE_ID, 
A.CENTERCODE, 
A.CENTERNAME,
A.INSTANCECHAIN,
A.S_CURRENCY_CODE,
B.MONTH,
B.YEAR
FROM DBO.t_student_detail SD WITH(NOLOCK) 
INNER JOIN T_Student_Center_Detail SCD WITH(NOLOCK) ON  SD.I_STUDENT_DETAIL_ID=SCD.I_STUDENT_DETAIL_ID
INNER JOIN @EEBCINITIAL A ON A.I_CENTRE_ID=SCD.I_CENTRE_ID
INNER JOIN @YEARMONTH B ON MONTH(SD.DT_CRTD_ON)=B.MONTH
AND YEAR(SD.DT_CRTD_ON)=B.YEAR WHERE SD.I_STATUS<>0 

UNION 

SELECT DISTINCT
A.I_CENTRE_ID, 
A.CENTERCODE, 
A.CENTERNAME,
A.INSTANCECHAIN,
A.S_CURRENCY_CODE,
B.MONTH,
B.YEAR
FROM DBO.T_INVOICE_PARENT IP WITH(NOLOCK) 
INNER JOIN @EEBCINITIAL A ON A.I_CENTRE_ID=IP.I_CENTRE_ID
INNER JOIN @YEARMONTH B ON MONTH(IP.DT_CRTD_ON)=B.MONTH
AND YEAR(IP.DT_CRTD_ON)=B.YEAR WHERE IP.I_STATUS<>0 

UNION 

SELECT DISTINCT
A.I_CENTRE_ID, 
A.CENTERCODE, 
A.CENTERNAME,
A.INSTANCECHAIN,
A.S_CURRENCY_CODE,
B.MONTH,
B.YEAR
FROM T_Receipt_Header RH WITH(NOLOCK) 
INNER JOIN @EEBCINITIAL A ON A.I_CENTRE_ID=RH.I_CENTRE_ID
INNER JOIN @YEARMONTH B ON MONTH(RH.Dt_Receipt_Date)=B.MONTH
AND YEAR(RH.Dt_Receipt_Date)=B.YEAR WHERE RH.I_STATUS<>0 

UNION 

SELECT DISTINCT
A.I_CENTRE_ID, 
A.CENTERCODE, 
A.CENTERNAME,
A.INSTANCECHAIN,
A.S_CURRENCY_CODE,
B.MONTH,
B.YEAR
FROM T_Receipt_Header RH WITH(NOLOCK) 
INNER JOIN @EEBCINITIAL A ON A.I_CENTRE_ID=RH.I_CENTRE_ID
INNER JOIN @YEARMONTH B ON MONTH(RH.Dt_Upd_On)=B.MONTH
AND YEAR(RH.Dt_Upd_On)=B.YEAR WHERE RH.I_STATUS = 0 
)
---

UPDATE @EEBCANALYSIS SET TOTAL_ENQUIRY = Z.CNT
FROM @EEBCANALYSIS P INNER JOIN
(
SELECT A.I_CENTRE_ID CID, B.MONTH M,B.YEAR Y,COUNT(SCD.I_ENQUIRY_REGN_ID) CNT
FROM @EEBCINITIAL A
INNER JOIN DBO.T_ENQUIRY_REGN_DETAIL SCD WITH(NOLOCK) 
ON SCD.I_CENTRE_ID=A.I_CENTRE_ID
INNER JOIN @YEARMONTH B 
ON MONTH(SCD.DT_CRTD_ON)=B.MONTH
AND YEAR(SCD.DT_CRTD_ON)=B.YEAR 
GROUP BY A.I_CENTRE_ID, B.MONTH,B.YEAR
) AS Z
ON P.I_CENTRE_ID = Z.CID
AND P.MONTH = Z.M
AND P.YEAR = Z.Y
---


UPDATE @EEBCANALYSIS SET TOTAL_ENROLL = Z.CNT
FROM @EEBCANALYSIS P INNER JOIN
(SELECT A.I_CENTRE_ID CID,B.MONTH M,B.YEAR Y,COUNT(IP.I_STUDENT_DETAIL_ID) CNT
FROM @EEBCINITIAL A
INNER JOIN DBO.T_STUDENT_CENTER_DETAIL SCD WITH(NOLOCK)
ON SCD.I_CENTRE_ID=A.I_CENTRE_ID
INNER JOIN DBO.T_INVOICE_PARENT IP WITH(NOLOCK)
ON IP.I_STUDENT_DETAIL_ID=SCD.I_STUDENT_DETAIL_ID
INNER JOIN @YEARMONTH B
ON MONTH(IP.Dt_Invoice_Date)=B.MONTH
AND YEAR(IP.Dt_Invoice_Date)=B.YEAR
GROUP BY A.I_CENTRE_ID,B.MONTH,B.YEAR
) AS Z
ON P.I_CENTRE_ID = Z.CID
AND P.MONTH = Z.M
AND P.YEAR = Z.Y

UPDATE @EEBCANALYSIS SET INVOICE_AMOUNT = ISNULL(Z.SUM1,0)
FROM @EEBCANALYSIS P INNER JOIN
(SELECT 
A.I_CENTRE_ID CID,
B.MONTH M,
B.YEAR Y, 
SUM(ISNULL(IP.N_INVOICE_AMOUNT,0)) SUM1
FROM @EEBCINITIAL A
INNER JOIN DBO.T_INVOICE_PARENT IP WITH(NOLOCK) ON A.I_CENTRE_ID = IP.I_CENTRE_ID AND IP.I_STATUS = 1
INNER JOIN @YEARMONTH B ON MONTH(IP.DT_INVOICE_DATE)=B.MONTH AND YEAR(IP.DT_INVOICE_DATE)=B.YEAR
GROUP BY A.I_CENTRE_ID,B.MONTH,B.YEAR
) AS Z
ON P.I_CENTRE_ID = Z.CID
AND P.MONTH = Z.M
AND P.YEAR = Z.Y



UPDATE @EEBCANALYSIS SET COLLECTION_AMOUNT = Z.SUM1
FROM @EEBCANALYSIS P INNER JOIN
(SELECT A.I_CENTRE_ID CID,B.MONTH M,B.YEAR Y, SUM(ISNULL(RH.N_RECEIPT_AMOUNT,0.00)) SUM1
FROM DBO.T_RECEIPT_HEADER RH WITH(NOLOCK)
INNER JOIN @EEBCINITIAL A
ON RH.I_CENTRE_ID = A.I_CENTRE_ID
INNER JOIN @YEARMONTH B
ON MONTH(RH.DT_RECEIPT_DATE)=B.MONTH
AND YEAR(RH.DT_RECEIPT_DATE)=B.YEAR
GROUP BY A.I_CENTRE_ID,B.MONTH,B.YEAR
) AS Z
ON P.I_CENTRE_ID = Z.CID
AND P.MONTH = Z.M
AND P.YEAR = Z.Y


UPDATE @EEBCANALYSIS SET COLLECTION_AMOUNT = ISNULL(COLLECTION_AMOUNT,0) - Z.SUM1
FROM @EEBCANALYSIS P INNER JOIN
(SELECT A.I_CENTRE_ID CID,B.MONTH M,B.YEAR Y, SUM(ISNULL(RH.N_RECEIPT_AMOUNT,0.00)) SUM1
FROM DBO.T_RECEIPT_HEADER RH WITH(NOLOCK)
INNER JOIN @EEBCINITIAL A
ON RH.I_CENTRE_ID = A.I_CENTRE_ID
AND RH.I_STATUS = 0
INNER JOIN @YEARMONTH B
ON MONTH(RH.DT_UPD_ON)=B.MONTH
AND YEAR(RH.DT_UPD_ON)=B.YEAR
GROUP BY A.I_CENTRE_ID,B.MONTH,B.YEAR
) AS Z
ON P.I_CENTRE_ID = Z.CID
AND P.MONTH = Z.M
AND P.YEAR = Z.Y


------------- Last Invoice No, Date
UPDATE @EEBCANALYSIS SET NoLastInvoice = Z.LastNo, DtLastInvoice = Z.LastDt
	FROM @EEBCANALYSIS P 
		INNER JOIN (SELECT A.I_CENTRE_ID CID,B.MONTH M,B.YEAR Y, Max(Dt_Invoice_Date) AS LastDt, Max(Cast(S_Invoice_No AS Bigint)) LastNo 
					FROM @EEBCINITIAL A
						INNER JOIN [AptechRetailDB].DBO.T_STUDENT_CENTER_DETAIL SCD WITH(NOLOCK) ON SCD.I_CENTRE_ID=A.I_CENTRE_ID
						INNER JOIN [AptechRetailDB].DBO.T_INVOICE_PARENT IP WITH(NOLOCK) ON IP.I_STUDENT_DETAIL_ID=SCD.I_STUDENT_DETAIL_ID
						INNER JOIN @YEARMONTH B ON MONTH(IP.Dt_Invoice_Date)=B.MONTH AND YEAR(IP.Dt_Invoice_Date)=B.YEAR
					GROUP BY A.I_CENTRE_ID,B.MONTH,B.YEAR
					) AS Z ON P.I_CENTRE_ID = Z.CID AND P.MONTH = Z.M AND P.YEAR = Z.Y

--------- Last Receipt No, Date --------------
UPDATE @EEBCANALYSIS SET NoLastReceipt = Z.LastNo, DtLastReceipt = Z.LastDt
FROM @EEBCANALYSIS P 
	INNER JOIN (SELECT A.I_CENTRE_ID CID,B.MONTH M,B.YEAR Y, Max(Dt_Receipt_Date) AS LastDt, 
														Max(Cast(Replace(S_Receipt_No, 'A', '') AS Bigint)) AS LastNo
				FROM [AptechRetailDB].DBO.T_RECEIPT_HEADER RH WITH(NOLOCK)
					INNER JOIN @EEBCINITIAL A ON RH.I_CENTRE_ID = A.I_CENTRE_ID
					INNER JOIN @YEARMONTH B ON MONTH(RH.DT_RECEIPT_DATE)=B.MONTH AND YEAR(RH.DT_RECEIPT_DATE)=B.YEAR
				GROUP BY A.I_CENTRE_ID,B.MONTH,B.YEAR
				) AS Z ON P.I_CENTRE_ID = Z.CID AND P.MONTH = Z.M AND P.YEAR = Z.Y



SELECT DISTINCT * FROM @EEBCANALYSIS WHERE I_CENTRE_ID IN
( SELECT I_CENTRE_ID FROM DBO.T_CENTRE_MASTER WHERE I_STATUS <> 0)

END TRY

BEGIN CATCH

DECLARE @ERRMSG NVARCHAR(4000), @ERRSEVERITY INT

SELECT @ERRMSG = ERROR_MESSAGE(),
@ERRSEVERITY = ERROR_SEVERITY()

RAISERROR(@ERRMSG, @ERRSEVERITY, 1)
END CATCH
