CREATE PROCEDURE [REPORT].[uspUserLoginDetailsReport]
(
@USERROLE VARCHAR (150)='*',
@TRUSTDOMAIN VARCHAR(150)='*',
@USERTYPE VARCHAR(150)='*',
@BRANDNAME VARCHAR (150)='*',
@CENTERID INT = 0,
@CENTERNAME VARCHAR(150)='*'
)
AS
BEGIN TRY
--exec [REPORT].[uspUserLoginDetailsReport] 'System Administrator','SYSTEMADMIN','TE','Company COMPUTER EDUCATION'
DECLARE @I_HIERARCHY_MASTER_ID INT
DECLARE @I_HIERARCHY_DETAIL_ID INT
DECLARE @S_TRUST_DOMAIN VARCHAR(50)
DECLARE @S_INSTANCE_NODE VARCHAR(50)
DECLARE @I_USER_ID INT
DECLARE @ID INT
DECLARE @BRANDID INT

SET NOCOUNT ON

CREATE TABLE #TABLEFORREPORT(
[ID] [INT] IDENTITY(1,1) NOT NULL,
[USERNAME] [VARCHAR](150) NOT NULL,
[LOGINID] [VARCHAR](50) NOT NULL,
[USERID] [INT] NULL,
[BRANDNAME] [VARCHAR](50) NULL,
[BRANDID] [INT] NULL,
[CENTREID] [int] null,
[CENTRENAME] [varchar] (100) null,
[USERTYPE] [VARCHAR](50) NULL,
[INSTANCENODE] [VARCHAR](50) NULL,
[TRUSTDOMAIN] [VARCHAR](50) NULL,
[USERROLE] [VARCHAR](50) NULL,
[CREATEDDATE] [DATETIME] NULL,
[VALIDFROM] [DATETIME] NULL,
[VALIDTO] [DATETIME] NULL
)

INSERT INTO #TABLEFORREPORT
(
[USERNAME],
[USERID],
[LOGINID],
[BRANDNAME],
[BRANDID] ,
[CENTREID],
[CENTRENAME],
[USERTYPE],
[INSTANCENODE],
[TRUSTDOMAIN],
[USERROLE],
[CREATEDDATE],
[VALIDFROM],
[VALIDTO]
)

SELECT DISTINCT
LTRIM(RTRIM((LTRIM(RTRIM(ISNULL(UM.S_FIRST_NAME,''))) + ' ' + LTRIM(RTRIM(ISNULL(UM.S_MIDDLE_NAME,''))) + ' ' + LTRIM(RTRIM(ISNULL(UM.S_LAST_NAME,'')))))) AS [USERNAME],
UM.I_USER_ID [USERID],
UM.S_LOGIN_ID [LOGINID],
BM.S_BRAND_NAME [BRANDNAME],
BM.I_BRAND_ID [BRANDID],
null [CENTREID],
null [CENTRENAME],
UTM.S_User_Type_Desc [USERTYPE],
NULL [INSTANCENODE],
NULL [TRUSTDOMAIN],
RM.S_ROLE_DESC [USERROLE],
UM.DT_CRTD_ON [CREATEDDATE],
UHD.DT_VALID_FROM [VALIDFROM],
UHD.DT_VALID_TO [VALIDTO]
FROM T_USER_MASTER UM
INNER JOIN T_USER_HIERARCHY_DETAILS UHD
ON UM.I_USER_ID=UHD.I_USER_ID
AND UHD.I_STATUS=1
-- AND UM.I_USER_ID <>1
AND UM.I_STATUS=1
INNER JOIN T_HIERARCHY_BRAND_DETAILS HBD
ON UHD.I_HIERARCHY_MASTER_ID=HBD.I_HIERARCHY_MASTER_ID
AND HBD.I_STATUS=1
INNER JOIN T_BRAND_MASTER BM
ON HBD.I_BRAND_ID=BM.I_BRAND_ID
AND HBD.I_STATUS=1
AND UHD.I_HIERARCHY_DETAIL_ID NOT IN
(SELECT I_HIERARCHY_DETAIL_ID FROM T_HIERARCHY_DETAILS WHERE S_HIERARCHY_NAME LIKE '%DUMMY%')
INNER JOIN T_USER_ROLE_DETAILS URD
ON UM.I_USER_ID=URD.I_USER_ID
INNER JOIN T_ROLE_MASTER RM
ON URD.I_ROLE_ID=RM.I_ROLE_ID
AND URD.I_STATUS=1
AND RM.I_STATUS=1
INNER JOIN dbo.T_User_Type_Master UTM
ON UTM.S_User_Type_Code = UM.S_USER_TYPE
WHERE BM.S_BRAND_NAME IN (
SELECT ISNULL((SELECT @BRANDNAME
EXCEPT
SELECT @BRANDNAME WHERE @BRANDNAME='*'),BM.S_BRAND_NAME))
AND UTM.S_USER_TYPE_DESC IN (
SELECT ISNULL((SELECT @USERTYPE
EXCEPT
SELECT @USERTYPE WHERE @USERTYPE='*'),UTM.S_USER_TYPE_DESC))
AND RM.S_ROLE_DESC IN (
SELECT ISNULL((SELECT @USERROLE
EXCEPT
SELECT @USERROLE WHERE @USERROLE='*'),RM.S_ROLE_DESC))

--SELECT * FROM #TABLEFORREPORT

DECLARE _CURSOR CURSOR FOR

SELECT
UHD.I_HIERARCHY_MASTER_ID,UHD.I_HIERARCHY_DETAIL_ID,UM.I_USER_ID,TEMP.ID,TEMP.BRANDID
FROM T_USER_MASTER UM
INNER JOIN T_USER_HIERARCHY_DETAILS UHD
ON UM.I_USER_ID=UHD.I_USER_ID
AND UM.I_STATUS=1
INNER JOIN #TABLEFORREPORT TEMP
ON UM.I_USER_ID=TEMP.USERID

OPEN _CURSOR
FETCH NEXT FROM _CURSOR INTO @I_HIERARCHY_MASTER_ID,@I_HIERARCHY_DETAIL_ID,@I_USER_ID,@ID,@BRANDID

WHILE @@FETCH_STATUS = 0
BEGIN

IF @I_HIERARCHY_MASTER_ID = 1
BEGIN
--S_TRUST_DOMAIN--
SELECT @S_TRUST_DOMAIN=S_HIERARCHY_NAME FROM T_HIERARCHY_DETAILS WHERE I_HIERARCHY_DETAIL_ID=@I_HIERARCHY_DETAIL_ID
UPDATE #TABLEFORREPORT
SET TRUSTDOMAIN=@S_TRUST_DOMAIN WHERE USERID=@I_USER_ID AND ID=@ID AND BRANDID=@BRANDID
END
ELSE
BEGIN
--S_INSTANCE_NODE--

SELECT DISTINCT @S_INSTANCE_NODE=S_HIERARCHY_NAME FROM T_HIERARCHY_DETAILS WHERE I_HIERARCHY_DETAIL_ID IN
(
SELECT
UHD.I_HIERARCHY_DETAIL_ID
FROM T_USER_MASTER UM
INNER JOIN T_USER_HIERARCHY_DETAILS UHD
ON UM.I_USER_ID=UHD.I_USER_ID
AND UM.I_STATUS=1
AND UM.I_USER_ID=@I_USER_ID
AND UHD.I_HIERARCHY_MASTER_ID IN
(
SELECT DISTINCT I_HIERARCHY_MASTER_ID FROM T_HIERARCHY_BRAND_DETAILS WHERE I_HIERARCHY_MASTER_ID IN
(
SELECT
UHD.I_HIERARCHY_MASTER_ID
FROM T_USER_MASTER UM
INNER JOIN T_USER_HIERARCHY_DETAILS UHD
ON UM.I_USER_ID=UHD.I_USER_ID
AND UM.I_STATUS=1
AND UM.I_USER_ID=@I_USER_ID
AND UHD.I_HIERARCHY_MASTER_ID <>1
)
AND I_BRAND_ID=@BRANDID AND I_STATUS=1
)
AND UHD.I_HIERARCHY_MASTER_ID <>1
)

UPDATE #TABLEFORREPORT
SET INSTANCENODE=@S_INSTANCE_NODE WHERE USERID=@I_USER_ID AND ID=@ID AND BRANDID=@BRANDID

END

FETCH NEXT FROM _CURSOR INTO @I_HIERARCHY_MASTER_ID,@I_HIERARCHY_DETAIL_ID,@I_USER_ID,@ID,@BRANDID
END

CLOSE _CURSOR
DEALLOCATE _CURSOR

--UPDATE CENTERID AND CENTERNAME--

UPDATE #TABLEFORREPORT
SET [CENTREID]=ED.I_CENTRE_ID,
[CENTRENAME]=CM.S_CENTER_NAME
FROM #TABLEFORREPORT TABLEFORREPORT
INNER JOIN T_USER_MASTER UM
ON TABLEFORREPORT.USERID=UM.I_USER_ID
INNER JOIN T_EMPLOYEE_DTLS ED
ON UM.I_REFERENCE_ID=ED.I_EMPLOYEE_ID
INNER JOIN T_CENTRE_MASTER CM
ON ED.I_CENTRE_ID=CM.I_CENTRE_ID

UPDATE #TABLEFORREPORT
SET [CENTREID]=SCD.I_CENTRE_ID,
[CENTRENAME]=CM.S_CENTER_NAME
FROM #TABLEFORREPORT TABLEFORREPORT
INNER JOIN T_USER_MASTER UM
ON TABLEFORREPORT.USERID=UM.I_USER_ID
INNER JOIN T_STUDENT_DETAIL ED
ON UM.I_REFERENCE_ID=ED.I_STUDENT_DETAIL_ID
INNER JOIN T_STUDENT_CENTER_DETAIL SCD
ON ED.I_STUDENT_DETAIL_ID=SCD.I_STUDENT_DETAIL_ID
INNER JOIN T_CENTRE_MASTER CM
ON SCD.I_CENTRE_ID=CM.I_CENTRE_ID


--SELECT * FROM #TABLEFORREPORT order by ID


DECLARE @STRSQL AS NVARCHAR(4000)

SET @STRSQL = N' SELECT ' + CHAR(13)
SET @STRSQL = @STRSQL + N' [USERNAME],' + CHAR(13)
SET @STRSQL = @STRSQL + N' [LOGINID],' + CHAR(13)
SET @STRSQL = @STRSQL + N' [BRANDNAME],' + CHAR(13)
SET @STRSQL = @STRSQL + N' [USERTYPE],' + CHAR(13)
SET @STRSQL = @STRSQL + N' [INSTANCENODE],' + CHAR(13)
SET @STRSQL = @STRSQL + N' [TRUSTDOMAIN],' + CHAR(13)
SET @STRSQL = @STRSQL + N' [USERROLE],' + CHAR(13)
SET @STRSQL = @STRSQL + N' [CREATEDDATE],' + CHAR(13)
SET @STRSQL = @STRSQL + N' [VALIDFROM],' + CHAR(13)
SET @STRSQL = @STRSQL + N' [VALIDTO]' + CHAR(13)
SET @STRSQL = @STRSQL + N' FROM ' + CHAR(13)
SET @STRSQL = @STRSQL + N' #TABLEFORREPORT' + CHAR(13)
SET @STRSQL = @STRSQL + N' WHERE ' + CHAR(13)
SET @STRSQL = @STRSQL + N' (USERROLE = ''' + @USERROLE + ''' OR ''' + @USERROLE + ''' = ''*'')' + CHAR(13)
SET @STRSQL = @STRSQL + N' AND (TRUSTDOMAIN = ''' + @TRUSTDOMAIN + ''' OR ''' + @TRUSTDOMAIN + ''' = ''*'')' + CHAR(13)
SET @STRSQL = @STRSQL + N' AND (USERTYPE = ''' + @USERTYPE + ''' OR ''' + @USERTYPE + ''' = ''*'')' + CHAR(13)
SET @STRSQL = @STRSQL + N' AND (BRANDNAME = ''' + @BRANDNAME + ''' OR ''' + @BRANDNAME + ''' = ''*'')' + CHAR(13)
SET @STRSQL = @STRSQL + N' AND (CENTREID = ' + CONVERT(VARCHAR,@CENTERID) + ' OR ' + CONVERT(VARCHAR,@CENTERID) + ' = 0)' + CHAR(13)
SET @STRSQL = @STRSQL + N' AND (CENTRENAME = ''' + @CENTERNAME + ''' OR ''' + @CENTERNAME + ''' = ''*'')' + CHAR(13)


--PRINT @STRSQL
EXECUTE SP_EXECUTESQL @STRSQL

DROP TABLE #TABLEFORREPORT
END TRY

BEGIN CATCH
--Error occurred:

DECLARE @ErrMsg NVARCHAR(4000), @ErrSeverity int
SELECT @ErrMsg = ERROR_MESSAGE(),
@ErrSeverity = ERROR_SEVERITY()

RAISERROR(@ErrMsg, @ErrSeverity, 1)
END CATCH
