CREATE TABLE [dbo].[AdvSPTemp] (
    [I_Student_Detail_ID]  INT             NULL,
    [S_Mobile_No]          NVARCHAR (MAX)  NULL,
    [S_Student_ID]         NVARCHAR (MAX)  NULL,
    [I_Roll_No]            INT             NULL,
    [S_Student_Name]       NVARCHAR (MAX)  NULL,
    [S_Invoice_No]         NVARCHAR (MAX)  NULL,
    [S_Receipt_No]         NVARCHAR (MAX)  NULL,
    [Dt_Invoice_Date]      DATETIME        NULL,
    [S_Component_Name]     NVARCHAR (MAX)  NULL,
    [S_Batch_Name]         NVARCHAR (MAX)  NULL,
    [S_Course_Name]        NVARCHAR (MAX)  NULL,
    [I_Center_ID]          INT             NULL,
    [S_Center_Name]        NVARCHAR (MAX)  NULL,
    [S_Brand_Name]         NVARCHAR (MAX)  NULL,
    [S_Cost_Center]        NVARCHAR (MAX)  NULL,
    [Due_Value]            REAL            NULL,
    [Dt_Installment_Date]  DATETIME        NULL,
    [I_Installment_No]     INT             NULL,
    [I_Parent_Invoice_ID]  INT             NULL,
    [I_Invoice_Detail_ID]  INT             NULL,
    [Revised_Invoice_Date] DATETIME        NULL,
    [Tax_Value]            DECIMAL (14, 2) NULL,
    [Total_Value]          DECIMAL (14, 2) NULL,
    [Amount_Paid]          DECIMAL (14, 2) NULL,
    [Tax_Paid]             DECIMAL (14, 2) NULL,
    [Total_Paid]           DECIMAL (14, 2) NULL,
    [MonthYear]            NVARCHAR (MAX)  NULL,
    [instanceChain]        NVARCHAR (MAX)  NULL
);

