CREATE TABLE [dbo].[BKP_T_Student_Detail] (
    [I_Student_Detail_ID]       INT             IDENTITY (1, 1) NOT NULL,
    [I_Enquiry_Regn_ID]         INT             NULL,
    [S_Student_ID]              NVARCHAR (MAX)  NULL,
    [S_Title]                   NVARCHAR (MAX)  NULL,
    [S_First_Name]              NVARCHAR (MAX)  NULL,
    [S_Middle_Name]             NVARCHAR (MAX)  NULL,
    [S_Last_Name]               NVARCHAR (MAX)  NULL,
    [S_Guardian_Name]           NVARCHAR (MAX)  NULL,
    [I_Guardian_Occupation_ID]  INT             NULL,
    [S_Guardian_Email_ID]       NVARCHAR (MAX)  NULL,
    [S_Guardian_Phone_No]       NVARCHAR (MAX)  NULL,
    [S_Guardian_Mobile_No]      NVARCHAR (MAX)  NULL,
    [I_Income_Group_ID]         INT             NULL,
    [Dt_Birth_Date]             DATETIME        NULL,
    [S_Age]                     NVARCHAR (MAX)  NULL,
    [S_Email_ID]                NVARCHAR (MAX)  NULL,
    [S_Phone_No]                NVARCHAR (MAX)  NULL,
    [S_Mobile_No]               NVARCHAR (MAX)  NULL,
    [C_Skip_Test]               CHAR (1)        NULL,
    [I_Occupation_ID]           INT             NULL,
    [I_Pref_Career_ID]          INT             NULL,
    [I_Qualification_Name_ID]   INT             NULL,
    [I_Stream_ID]               INT             NULL,
    [S_Curr_Address1]           NVARCHAR (MAX)  NULL,
    [S_Curr_Address2]           NVARCHAR (MAX)  NULL,
    [I_Curr_Country_ID]         INT             NULL,
    [I_Curr_State_ID]           INT             NULL,
    [I_Curr_City_ID]            INT             NULL,
    [S_Curr_Area]               NVARCHAR (MAX)  NULL,
    [S_Curr_Pincode]            NVARCHAR (MAX)  NULL,
    [S_Perm_Address1]           NVARCHAR (MAX)  NULL,
    [S_Perm_Address2]           NVARCHAR (MAX)  NULL,
    [I_Perm_Country_ID]         INT             NULL,
    [I_Perm_State_ID]           INT             NULL,
    [I_Perm_City_ID]            INT             NULL,
    [S_Perm_Area]               NVARCHAR (MAX)  NULL,
    [S_Perm_Pincode]            NVARCHAR (MAX)  NULL,
    [I_Status]                  INT             NOT NULL,
    [S_Crtd_By]                 NVARCHAR (MAX)  NULL,
    [S_Upd_By]                  NVARCHAR (MAX)  NULL,
    [Dt_Crtd_On]                DATETIME        NULL,
    [Dt_Upd_On]                 DATETIME        NULL,
    [S_Conduct_Code]            NVARCHAR (MAX)  NULL,
    [S_Is_Corporate]            NVARCHAR (MAX)  NULL,
    [I_Corporate_ID]            INT             NULL,
    [I_Residence_Area_ID]       INT             NULL,
    [I_RollNo]                  INT             NULL,
    [I_Marital_Status_ID]       INT             NULL,
    [I_Transport_ID]            INT             NULL,
    [I_room_ID]                 INT             NULL,
    [I_House_ID]                INT             NULL,
    [I_Route_ID]                INT             NULL,
    [B_Is_APAI_Acc_Settled]     BIT             NULL,
    [Dt_Transport_Deactivation] DATETIME        NULL,
    [B_IsBooking]               INT             NULL,
    [B_HasTakenLoan]            BIT             NULL,
    [I_DiscountType_ID]         INT             NULL,
    [S_Ext_Email_ID]            NVARCHAR (MAX)  NULL,
    [IsDropOut]                 BIT             NULL,
    [IsWaiting]                 BIT             NULL,
    [IsDefaulter]               BIT             NULL,
    [IsOnLeave]                 BIT             NULL,
    [IsCompleted]               BIT             NULL,
    [IsDiscontinued]            BIT             NULL,
    [N_DueAmount]               DECIMAL (14, 2) NULL,
    [S_OrgEmailID]              NVARCHAR (MAX)  NULL,
    [S_OrgEmailPassword]        NVARCHAR (MAX)  NULL,
    [IsPreDefaulter]            DATETIME        NULL,
    [IsPaymentDue]              BIT             NULL,
    [I_IsPreDefaulter]          INT             NULL,
    [DefaulterCourses]          NVARCHAR (MAX)  NULL,
    [PreDefaulterCourses]       NVARCHAR (MAX)  NULL,
    [PaymentDueCourses]         NVARCHAR (MAX)  NULL
);

