CREATE TABLE [dbo].[Mig_NPF_Enquiry] (
    [Enquiry_Type]      NVARCHAR (255) NULL,
    [Title]             NVARCHAR (255) NULL,
    [First_Name]        NVARCHAR (255) NULL,
    [Middle_Name]       NVARCHAR (255) NULL,
    [Last_Name]         NVARCHAR (255) NULL,
    [Dt_Birth_Date]     NVARCHAR (255) NULL,
    [Age]               NVARCHAR (255) NULL,
    [Email_ID]          NVARCHAR (255) NULL,
    [Student_Mobile_No] NVARCHAR (255) NULL,
    [Current_City]      NVARCHAR (255) NULL,
    [Curr_State]        NVARCHAR (255) NULL,
    [Curr_Country]      NVARCHAR (255) NULL,
    [Curr_Address1]     NVARCHAR (255) NULL,
    [Curr_Address2]     NVARCHAR (255) NULL,
    [Curr_Pincode]      FLOAT (53)     NULL,
    [Perm_Address1]     NVARCHAR (255) NULL,
    [Perm_Address2]     NVARCHAR (255) NULL,
    [Perm_Pincode]      FLOAT (53)     NULL,
    [Perm_City]         NVARCHAR (255) NULL,
    [Perm_State]        NVARCHAR (255) NULL,
    [Perm_Country]      NVARCHAR (255) NULL,
    [Perm_Area]         NVARCHAR (255) NULL,
    [Father_Name]       NVARCHAR (255) NULL,
    [Mother_Name]       NVARCHAR (255) NULL,
    [Student_Gender]    NVARCHAR (255) NULL,
    [Religion]          NVARCHAR (255) NULL,
    [Father_Phone]      FLOAT (53)     NULL,
    [Mother_Phone]      FLOAT (53)     NULL,
    [Father_Email]      NVARCHAR (255) NULL,
    [Mother_Email]      NVARCHAR (255) NULL,
    [School Programme]  NVARCHAR (255) NULL,
    [Class Name]        NVARCHAR (255) NULL,
    [Stream]            NVARCHAR (255) NULL,
    [Section]           NVARCHAR (255) NULL,
    [Registration_Fee]  FLOAT (53)     NULL,
    [Payment Date]      NVARCHAR (255) NULL,
    [ID]                INT            IDENTITY (1, 1) NOT NULL,
    [EnquiryID]         INT            NULL,
    [Is_Processed]      BIT            NULL
);

