CREATE TABLE [dbo].[razorPayPaymentTransactions] (
    [entity_id]      NVARCHAR (MAX)  NULL,
    [type]           NVARCHAR (MAX)  NULL,
    [debit]          DECIMAL (18, 2) NULL,
    [credit]         DECIMAL (18, 2) NULL,
    [amount]         DECIMAL (18, 2) NULL,
    [currency]       NVARCHAR (MAX)  NULL,
    [fee]            DECIMAL (18, 2) NULL,
    [tax]            DECIMAL (18, 2) NULL,
    [on_hold]        BIT             NULL,
    [settled]        BIT             NULL,
    [created_at]     DATETIME        NULL,
    [settled_at]     DATETIME        NULL,
    [settlement_id]  NVARCHAR (MAX)  NULL,
    [description]    TEXT            NULL,
    [notes]          TEXT            NULL,
    [payment_id]     NVARCHAR (MAX)  NULL,
    [arn]            NVARCHAR (MAX)  NULL,
    [settlement_utr] NVARCHAR (MAX)  NULL,
    [order_id]       NVARCHAR (MAX)  NULL,
    [order_receipt]  NVARCHAR (MAX)  NULL,
    [method]         NVARCHAR (MAX)  NULL,
    [upi_flow]       NVARCHAR (MAX)  NULL,
    [card_network]   NVARCHAR (MAX)  NULL,
    [card_issuer]    NVARCHAR (MAX)  NULL,
    [card_type]      NVARCHAR (MAX)  NULL,
    [dispute_id]     NVARCHAR (MAX)  NULL,
    [additional_utr] NVARCHAR (MAX)  NULL
);

