CREATE TABLE [dbo].[T_Course_Master] (
    [I_Course_ID]              INT            IDENTITY (1, 1) NOT NULL,
    [I_Brand_ID]               INT            NULL,
    [I_CourseFamily_ID]        INT            NULL,
    [S_Course_Code]            NVARCHAR (MAX) NULL,
    [S_Course_Name]            NVARCHAR (MAX) NULL,
    [S_Course_Desc]            NVARCHAR (MAX) NULL,
    [I_Grading_Pattern_ID]     INT            NULL,
    [I_No_Of_Session]          INT            NULL,
    [I_Certificate_ID]         INT            NULL,
    [I_Document_ID]            INT            NULL,
    [C_AptitudeTestReqd]       CHAR (1)       NULL,
    [C_IsCareerCourse]         CHAR (1)       NULL,
    [C_IsShortTermCourse]      CHAR (1)       NULL,
    [C_IsPlacementApplicable]  CHAR (1)       NULL,
    [I_Is_Editable]            INT            NULL,
    [I_Status]                 INT            NULL,
    [S_Crtd_By]                NVARCHAR (MAX) NULL,
    [S_Upd_By]                 NVARCHAR (MAX) NULL,
    [Dt_Crtd_On]               DATETIME       NULL,
    [Dt_Upd_On]                DATETIME       NULL,
    [I_Is_Upgrade_Course]      INT            NULL,
    [I_Is_Dropout_Allowed]     CHAR (1)       NULL,
    [I_No_Of_Days]             INT            NULL,
    [I_Is_ST_Applicable]       CHAR (1)       NULL,
    [I_Min_Week_For_Placement] INT            NULL,
    [I_Max_Week_For_Placement] INT            NULL,
    [S_Course_Category]        NVARCHAR (MAX) NULL,
    [B_IsAdmissionCourse]      BIT            NULL,
    [I_Language_ID]            INT            NULL,
    [I_Language_Name]          NVARCHAR (MAX) NULL,
    CONSTRAINT [PK__T_Course_Master__4DD54A14] PRIMARY KEY CLUSTERED ([I_Course_ID] ASC)
);

