CREATE TABLE [dbo].[T_Enquiry_External_Additional_Details] (
    [ID]                    INT            IDENTITY (1, 1) NOT NULL,
    [PreEnquiryID]          INT            NOT NULL,
    [ExtApplicationID]      NVARCHAR (MAX) NULL,
    [FirstName]             NVARCHAR (MAX) NOT NULL,
    [MiddleName]            NVARCHAR (MAX) NULL,
    [LastName]              NVARCHAR (MAX) NULL,
    [Centre]                NVARCHAR (MAX) NULL,
    [MobileNo]              NVARCHAR (MAX) NULL,
    [EmailID]               NVARCHAR (MAX) NULL,
    [AlternateMobileNo]     NVARCHAR (MAX) NULL,
    [DateofBirth]           DATETIME       NULL,
    [SalesDisposition]      NVARCHAR (MAX) NULL,
    [DateofMaturityCC]      DATETIME       NULL,
    [DateofMaturitySales]   DATETIME       NULL,
    [Counsellor]            NVARCHAR (MAX) NULL,
    [LeadCreatedBy]         NVARCHAR (MAX) NULL,
    [Origin]                NVARCHAR (MAX) NULL,
    [PrimaryTrafficChannel] NVARCHAR (MAX) NULL,
    [InfoSource]            NVARCHAR (MAX) NULL,
    [InfoMedium]            NVARCHAR (MAX) NULL,
    [InfoCampaign]          NVARCHAR (MAX) NULL,
    [HighestQualification]  NVARCHAR (MAX) NULL,
    [Country]               NVARCHAR (MAX) NULL,
    [State]                 NVARCHAR (MAX) NULL,
    [District]              NVARCHAR (MAX) NULL,
    [City]                  NVARCHAR (MAX) NULL,
    [Pincode]               NVARCHAR (MAX) NULL,
    [UserRegistrationDate]  DATETIME       NULL,
    [ExtSource]             NVARCHAR (MAX) NULL,
    [CreatedBy]             NVARCHAR (MAX) NULL,
    [CreatedOn]             DATETIME       NULL
);

