CREATE TABLE [dbo].[T_Enquiry_Regn_Detail] (
    [I_Enquiry_Regn_ID]          INT             IDENTITY (1, 1) NOT NULL,
    [I_Centre_Id]                INT             NULL,
    [I_Occupation_ID]            INT             NULL,
    [I_Pref_Career_ID]           INT             NULL,
    [I_Enquiry_Status_Code]      INT             NULL,
    [I_Info_Source_ID]           INT             NULL,
    [I_Enquiry_Type_ID]          INT             NULL,
    [S_Enquiry_No]               NVARCHAR (MAX)  NULL,
    [S_Is_Corporate]             NVARCHAR (MAX)  NULL,
    [S_Enquiry_Desc]             NVARCHAR (MAX)  NULL,
    [S_Title]                    NVARCHAR (MAX)  NULL,
    [S_First_Name]               NVARCHAR (MAX)  NULL,
    [S_Middle_Name]              NVARCHAR (MAX)  NULL,
    [S_Last_Name]                NVARCHAR (MAX)  NULL,
    [Dt_Birth_Date]              DATETIME        NULL,
    [S_Age]                      NVARCHAR (MAX)  NULL,
    [I_Qualification_Name_ID]    INT             NULL,
    [C_Skip_Test]                CHAR (1)        NULL,
    [I_Stream_ID]                INT             NULL,
    [I_Aptitude_Marks]           INT             NULL,
    [S_Email_ID]                 NVARCHAR (MAX)  NULL,
    [S_Phone_No]                 NVARCHAR (MAX)  NULL,
    [S_Mobile_No]                NVARCHAR (MAX)  NULL,
    [I_Curr_City_ID]             INT             NULL,
    [I_Curr_State_ID]            INT             NULL,
    [I_Curr_Country_ID]          INT             NULL,
    [S_Guardian_Name]            NVARCHAR (MAX)  NULL,
    [I_Guardian_Occupation_ID]   INT             NULL,
    [S_Guardian_Email_ID]        NVARCHAR (MAX)  NULL,
    [S_Guardian_Phone_No]        NVARCHAR (MAX)  NULL,
    [S_Guardian_Mobile_No]       NVARCHAR (MAX)  NULL,
    [I_Income_Group_ID]          INT             NULL,
    [S_Curr_Address1]            NVARCHAR (MAX)  NULL,
    [S_Curr_Address2]            NVARCHAR (MAX)  NULL,
    [S_Curr_Pincode]             NVARCHAR (MAX)  NULL,
    [S_Curr_Area]                NVARCHAR (MAX)  NULL,
    [S_Perm_Address1]            NVARCHAR (MAX)  NULL,
    [S_Perm_Address2]            NVARCHAR (MAX)  NULL,
    [S_Perm_Pincode]             NVARCHAR (MAX)  NULL,
    [I_Perm_City_ID]             INT             NULL,
    [I_Perm_State_ID]            INT             NULL,
    [I_Perm_Country_ID]          INT             NULL,
    [S_Perm_Area]                NVARCHAR (MAX)  NULL,
    [S_Crtd_By]                  NVARCHAR (MAX)  NULL,
    [S_Upd_By]                   NVARCHAR (MAX)  NULL,
    [Dt_Crtd_On]                 DATETIME        NULL,
    [Dt_Upd_On]                  DATETIME        NULL,
    [I_Corporate_ID]             INT             NULL,
    [I_Corporate_Plan_ID]        INT             NULL,
    [I_Caste_ID]                 INT             NULL,
    [S_Student_Photo]            NVARCHAR (MAX)  NULL,
    [I_Residence_Area_ID]        INT             NULL,
    [S_Father_Name]              NVARCHAR (MAX)  NULL,
    [S_Mother_Name]              NVARCHAR (MAX)  NULL,
    [B_IsPreEnquiry]             BIT             NULL,
    [I_Sex_ID]                   INT             NULL,
    [I_Native_Language_ID]       INT             NULL,
    [I_Nationality_ID]           INT             NULL,
    [I_Religion_ID]              INT             NULL,
    [I_Marital_Status_ID]        INT             NULL,
    [I_Blood_Group_ID]           INT             NULL,
    [I_Father_Qualification_ID]  INT             NULL,
    [I_Father_Occupation_ID]     INT             NULL,
    [I_Father_Business_Type_ID]  INT             NULL,
    [S_Father_Company_Name]      NVARCHAR (MAX)  NULL,
    [S_Father_Designation]       NVARCHAR (MAX)  NULL,
    [S_Father_Office_Phone]      NVARCHAR (MAX)  NULL,
    [I_Father_Income_Group_ID]   INT             NULL,
    [S_Father_Photo]             NVARCHAR (MAX)  NULL,
    [S_Father_Office_Address]    NVARCHAR (MAX)  NULL,
    [I_Mother_Qualification_ID]  INT             NULL,
    [I_Mother_Occupation_ID]     INT             NULL,
    [I_Mother_Business_Type_ID]  INT             NULL,
    [S_Mother_Designation]       NVARCHAR (MAX)  NULL,
    [S_Mother_Company_Name]      NVARCHAR (MAX)  NULL,
    [S_Mother_Office_Address]    NVARCHAR (MAX)  NULL,
    [S_Mother_Office_Phone]      NVARCHAR (MAX)  NULL,
    [I_Mother_Income_Group_ID]   INT             NULL,
    [S_Mother_Photo]             NVARCHAR (MAX)  NULL,
    [S_Guardian_Relationship]    NVARCHAR (MAX)  NULL,
    [S_Guardian_Address]         NVARCHAR (MAX)  NULL,
    [I_Monthly_Family_Income_ID] INT             NULL,
    [B_Can_Sponsor_Education]    BIT             NULL,
    [S_Sibling_ID]               NVARCHAR (MAX)  NULL,
    [B_Has_Given_Exam]           BIT             NULL,
    [I_Attempts]                 INT             NULL,
    [S_Other_Institute]          NVARCHAR (MAX)  NULL,
    [N_Duration]                 DECIMAL (18, 2) NULL,
    [I_Seat_Type_ID]             INT             NULL,
    [I_Enrolment_Type_ID]        INT             NULL,
    [S_Enrolment_No]             NVARCHAR (MAX)  NULL,
    [I_Rank_Obtained]            INT             NULL,
    [S_Univ_Registration_No]     NVARCHAR (MAX)  NULL,
    [S_Univ_Roll_No]             NVARCHAR (MAX)  NULL,
    [I_Scholar_Type_ID]          INT             NULL,
    [S_Second_Language_Opted]    NVARCHAR (MAX)  NULL,
    [S_Physical_Ailment]         NVARCHAR (MAX)  NULL,
    [S_Form_No]                  NVARCHAR (MAX)  NULL,
    [B_IsLateral]                BIT             NULL,
    [I_PreEnquiryFor]            INT             NULL,
    [I_Relevence_ID]             INT             NULL,
    [N_Test_Score]               DECIMAL (14, 1) NULL,
    [Enquiry_Date]               DATETIME        NULL,
    [Enquiry_Crtd_By]            NVARCHAR (MAX)  NULL,
    [PreEnquiryDate]             DATETIME        NULL,
    [PreEnquiry_Crtd_By]         NVARCHAR (MAX)  NULL,
    [CustomerID]                 NVARCHAR (MAX)  NULL,
    [RegID]                      INT             NULL,
    [I_Enq_PrevD_ID]             INT             NULL,
    [S_Father_Mobile_No]         NVARCHAR (MAX)  NULL,
    [S_Mother_Mobile_No]         NVARCHAR (MAX)  NULL,
    [S_Father_Email]             NVARCHAR (MAX)  NULL,
    [S_Mother_Email]             NVARCHAR (MAX)  NULL,
    [App_Payment_Status]         BIT             NULL,
    [R_I_AdmStgTypeID]           INT             NULL,
    [I_Is_Active]                BIT             NULL,
    [Is_Sibling]                 BIT             NULL,
    [Is_Prev_Academy]            BIT             NULL,
    [R_I_School_Session_ID]      INT             NULL,
    [I_School_Group_ID]          INT             NULL,
    [I_Class_ID]                 INT             NULL,
    [I_ERP_Entry]                BIT             NULL,
    [I_ERP_Crtd_By]              INT             NULL,
    [I_ERP_Updt_By]              INT             NULL,
    [I_Tab_No]                   INT             CONSTRAINT [DF_T_Enquiry_Regn_Detail_I_Tab_No] DEFAULT ((0)) NULL,
    [Dt_PaymentDate]             DATETIME        NULL,
    [I_Brand_ID]                 INT             NULL,
    CONSTRAINT [PK__T_Enquiry_Regn_D__02932B16] PRIMARY KEY CLUSTERED ([I_Enquiry_Regn_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [Ix_B_IsPreEnquiry]
    ON [dbo].[T_Enquiry_Regn_Detail]([B_IsPreEnquiry] ASC, [I_ERP_Entry] ASC, [App_Payment_Status] ASC)
    INCLUDE([I_Enquiry_Regn_ID], [I_Centre_Id], [I_Info_Source_ID], [R_I_AdmStgTypeID], [I_Class_ID]);


GO
CREATE TRIGGER [dbo].[TUPDATE_T_Enquiry_Regn_Detail] ON [dbo].[T_Enquiry_Regn_Detail] AFTER UPDATE ASBEGININSERT INTO T_Enquiry_Regn_Detail_A(I_Enquiry_Regn_ID,I_Centre_Id,I_Occupation_ID,I_Pref_Career_ID,I_Enquiry_Status_Code,I_Info_Source_ID,I_Enquiry_Type_ID,S_Enquiry_No,S_Is_Corporate,S_Enquiry_Desc,S_Title,S_First_Name,S_Middle_Name,S_Last_Name,Dt_Birth_Date,S_Age,I_Qualification_Name_ID,C_Skip_Test,I_Stream_ID,I_Aptitude_Marks,S_Email_ID,S_Phone_No,S_Mobile_No,I_Curr_City_ID,I_Curr_State_ID,I_Curr_Country_ID,S_Guardian_Name,I_Guardian_Occupation_ID,S_Guardian_Email_ID,S_Guardian_Phone_No,S_Guardian_Mobile_No,I_Income_Group_ID,S_Curr_Address1,S_Curr_Address2,S_Curr_Pincode,S_Curr_Area,S_Perm_Address1,S_Perm_Address2,S_Perm_Pincode,I_Perm_City_ID,I_Perm_State_ID,I_Perm_Country_ID,S_Perm_Area,S_Crtd_By,S_Upd_By,Dt_Crtd_On,Dt_Upd_On,I_Corporate_ID,I_Corporate_Plan_ID,I_Caste_ID,S_Student_Photo,I_Residence_Area_ID,S_Father_Name,S_Mother_Name,B_IsPreEnquiry,I_Sex_ID,I_Native_Language_ID,I_Nationality_ID,I_Religion_ID,I_Marital_Status_ID,I_Blood_Group_ID,I_Father_Qualification_ID,I_Father_Occupation_ID,I_Father_Business_Type_ID,S_Father_Company_Name,S_Father_Designation,S_Father_Office_Phone,I_Father_Income_Group_ID,S_Father_Photo,S_Father_Office_Address,I_Mother_Qualification_ID,I_Mother_Occupation_ID,I_Mother_Business_Type_ID,S_Mother_Designation,S_Mother_Company_Name,S_Mother_Office_Address,S_Mother_Office_Phone,I_Mother_Income_Group_ID,S_Mother_Photo,S_Guardian_Relationship,S_Guardian_Address,I_Monthly_Family_Income_ID,B_Can_Sponsor_Education,S_Sibling_ID,B_Has_Given_Exam,I_Attempts,S_Other_Institute,N_Duration,I_Seat_Type_ID,I_Enrolment_Type_ID,S_Enrolment_No,I_Rank_Obtained,S_Univ_Registration_No,S_Univ_Roll_No,I_Scholar_Type_ID,S_Second_Language_Opted,S_Physical_Ailment,S_Form_No,B_IsLateral,I_PreEnquiryFor,AuditedOn,AuditType)SELECT I_Enquiry_Regn_ID,I_Centre_Id,I_Occupation_ID,I_Pref_Career_ID,I_Enquiry_Status_Code,I_Info_Source_ID,I_Enquiry_Type_ID,S_Enquiry_No,S_Is_Corporate,S_Enquiry_Desc,S_Title,S_First_Name,S_Middle_Name,S_Last_Name,Dt_Birth_Date,S_Age,I_Qualification_Name_ID,C_Skip_Test,I_Stream_ID,I_Aptitude_Marks,S_Email_ID,S_Phone_No,S_Mobile_No,I_Curr_City_ID,I_Curr_State_ID,I_Curr_Country_ID,S_Guardian_Name,I_Guardian_Occupation_ID,S_Guardian_Email_ID,S_Guardian_Phone_No,S_Guardian_Mobile_No,I_Income_Group_ID,S_Curr_Address1,S_Curr_Address2,S_Curr_Pincode,S_Curr_Area,S_Perm_Address1,S_Perm_Address2,S_Perm_Pincode,I_Perm_City_ID,I_Perm_State_ID,I_Perm_Country_ID,S_Perm_Area,S_Crtd_By,S_Upd_By,Dt_Crtd_On,Dt_Upd_On,I_Corporate_ID,I_Corporate_Plan_ID,I_Caste_ID,S_Student_Photo,I_Residence_Area_ID,S_Father_Name,S_Mother_Name,B_IsPreEnquiry,I_Sex_ID,I_Native_Language_ID,I_Nationality_ID,I_Religion_ID,I_Marital_Status_ID,I_Blood_Group_ID,I_Father_Qualification_ID,I_Father_Occupation_ID,I_Father_Business_Type_ID,S_Father_Company_Name,S_Father_Designation,S_Father_Office_Phone,I_Father_Income_Group_ID,S_Father_Photo,S_Father_Office_Address,I_Mother_Qualification_ID,I_Mother_Occupation_ID,I_Mother_Business_Type_ID,S_Mother_Designation,S_Mother_Company_Name,S_Mother_Office_Address,S_Mother_Office_Phone,I_Mother_Income_Group_ID,S_Mother_Photo,S_Guardian_Relationship,S_Guardian_Address,I_Monthly_Family_Income_ID,B_Can_Sponsor_Education,S_Sibling_ID,B_Has_Given_Exam,I_Attempts,S_Other_Institute,N_Duration,I_Seat_Type_ID,I_Enrolment_Type_ID,S_Enrolment_No,I_Rank_Obtained,S_Univ_Registration_No,S_Univ_Roll_No,I_Scholar_Type_ID,S_Second_Language_Opted,S_Physical_Ailment,S_Form_No,B_IsLateral,I_PreEnquiryFor, GETDATE(), 'U'FROM DELETED IEND
GO
CREATE TRIGGER [dbo].[TDELETE_T_Enquiry_Regn_Detail] ON [dbo].[T_Enquiry_Regn_Detail] AFTER DELETE ASBEGININSERT INTO T_Enquiry_Regn_Detail_A(I_Enquiry_Regn_ID,I_Centre_Id,I_Occupation_ID,I_Pref_Career_ID,I_Enquiry_Status_Code,I_Info_Source_ID,I_Enquiry_Type_ID,S_Enquiry_No,S_Is_Corporate,S_Enquiry_Desc,S_Title,S_First_Name,S_Middle_Name,S_Last_Name,Dt_Birth_Date,S_Age,I_Qualification_Name_ID,C_Skip_Test,I_Stream_ID,I_Aptitude_Marks,S_Email_ID,S_Phone_No,S_Mobile_No,I_Curr_City_ID,I_Curr_State_ID,I_Curr_Country_ID,S_Guardian_Name,I_Guardian_Occupation_ID,S_Guardian_Email_ID,S_Guardian_Phone_No,S_Guardian_Mobile_No,I_Income_Group_ID,S_Curr_Address1,S_Curr_Address2,S_Curr_Pincode,S_Curr_Area,S_Perm_Address1,S_Perm_Address2,S_Perm_Pincode,I_Perm_City_ID,I_Perm_State_ID,I_Perm_Country_ID,S_Perm_Area,S_Crtd_By,S_Upd_By,Dt_Crtd_On,Dt_Upd_On,I_Corporate_ID,I_Corporate_Plan_ID,I_Caste_ID,S_Student_Photo,I_Residence_Area_ID,S_Father_Name,S_Mother_Name,B_IsPreEnquiry,I_Sex_ID,I_Native_Language_ID,I_Nationality_ID,I_Religion_ID,I_Marital_Status_ID,I_Blood_Group_ID,I_Father_Qualification_ID,I_Father_Occupation_ID,I_Father_Business_Type_ID,S_Father_Company_Name,S_Father_Designation,S_Father_Office_Phone,I_Father_Income_Group_ID,S_Father_Photo,S_Father_Office_Address,I_Mother_Qualification_ID,I_Mother_Occupation_ID,I_Mother_Business_Type_ID,S_Mother_Designation,S_Mother_Company_Name,S_Mother_Office_Address,S_Mother_Office_Phone,I_Mother_Income_Group_ID,S_Mother_Photo,S_Guardian_Relationship,S_Guardian_Address,I_Monthly_Family_Income_ID,B_Can_Sponsor_Education,S_Sibling_ID,B_Has_Given_Exam,I_Attempts,S_Other_Institute,N_Duration,I_Seat_Type_ID,I_Enrolment_Type_ID,S_Enrolment_No,I_Rank_Obtained,S_Univ_Registration_No,S_Univ_Roll_No,I_Scholar_Type_ID,S_Second_Language_Opted,S_Physical_Ailment,S_Form_No,B_IsLateral,I_PreEnquiryFor,AuditedOn,AuditType)SELECT I_Enquiry_Regn_ID,I_Centre_Id,I_Occupation_ID,I_Pref_Career_ID,I_Enquiry_Status_Code,I_Info_Source_ID,I_Enquiry_Type_ID,S_Enquiry_No,S_Is_Corporate,S_Enquiry_Desc,S_Title,S_First_Name,S_Middle_Name,S_Last_Name,Dt_Birth_Date,S_Age,I_Qualification_Name_ID,C_Skip_Test,I_Stream_ID,I_Aptitude_Marks,S_Email_ID,S_Phone_No,S_Mobile_No,I_Curr_City_ID,I_Curr_State_ID,I_Curr_Country_ID,S_Guardian_Name,I_Guardian_Occupation_ID,S_Guardian_Email_ID,S_Guardian_Phone_No,S_Guardian_Mobile_No,I_Income_Group_ID,S_Curr_Address1,S_Curr_Address2,S_Curr_Pincode,S_Curr_Area,S_Perm_Address1,S_Perm_Address2,S_Perm_Pincode,I_Perm_City_ID,I_Perm_State_ID,I_Perm_Country_ID,S_Perm_Area,S_Crtd_By,S_Upd_By,Dt_Crtd_On,Dt_Upd_On,I_Corporate_ID,I_Corporate_Plan_ID,I_Caste_ID,S_Student_Photo,I_Residence_Area_ID,S_Father_Name,S_Mother_Name,B_IsPreEnquiry,I_Sex_ID,I_Native_Language_ID,I_Nationality_ID,I_Religion_ID,I_Marital_Status_ID,I_Blood_Group_ID,I_Father_Qualification_ID,I_Father_Occupation_ID,I_Father_Business_Type_ID,S_Father_Company_Name,S_Father_Designation,S_Father_Office_Phone,I_Father_Income_Group_ID,S_Father_Photo,S_Father_Office_Address,I_Mother_Qualification_ID,I_Mother_Occupation_ID,I_Mother_Business_Type_ID,S_Mother_Designation,S_Mother_Company_Name,S_Mother_Office_Address,S_Mother_Office_Phone,I_Mother_Income_Group_ID,S_Mother_Photo,S_Guardian_Relationship,S_Guardian_Address,I_Monthly_Family_Income_ID,B_Can_Sponsor_Education,S_Sibling_ID,B_Has_Given_Exam,I_Attempts,S_Other_Institute,N_Duration,I_Seat_Type_ID,I_Enrolment_Type_ID,S_Enrolment_No,I_Rank_Obtained,S_Univ_Registration_No,S_Univ_Roll_No,I_Scholar_Type_ID,S_Second_Language_Opted,S_Physical_Ailment,S_Form_No,B_IsLateral,I_PreEnquiryFor, GETDATE(), 'D'FROM DELETED IEND