CREATE TABLE [dbo].[T_Enquiry_Regn_Detail_A] (
    [I_Enquiry_Regn_ID]          INT             NOT NULL,
    [I_Centre_Id]                INT             NULL,
    [I_Occupation_ID]            INT             NULL,
    [I_Pref_Career_ID]           INT             NULL,
    [I_Enquiry_Status_Code]      INT             NULL,
    [I_Info_Source_ID]           INT             NULL,
    [I_Enquiry_Type_ID]          INT             NULL,
    [S_Enquiry_No]               NVARCHAR (MAX)  NULL,
    [S_Is_Corporate]             NVARCHAR (MAX)  NULL,
    [S_Enquiry_Desc]             NVARCHAR (MAX)  NULL,
    [S_Title]                    NVARCHAR (MAX)  NULL,
    [S_First_Name]               NVARCHAR (MAX)  NULL,
    [S_Middle_Name]              NVARCHAR (MAX)  NULL,
    [S_Last_Name]                NVARCHAR (MAX)  NULL,
    [Dt_Birth_Date]              DATETIME        NULL,
    [S_Age]                      NVARCHAR (MAX)  NULL,
    [I_Qualification_Name_ID]    INT             NULL,
    [C_Skip_Test]                CHAR (1)        NULL,
    [I_Stream_ID]                INT             NULL,
    [I_Aptitude_Marks]           INT             NULL,
    [S_Email_ID]                 NVARCHAR (MAX)  NULL,
    [S_Phone_No]                 NVARCHAR (MAX)  NULL,
    [S_Mobile_No]                NVARCHAR (MAX)  NULL,
    [I_Curr_City_ID]             INT             NULL,
    [I_Curr_State_ID]            INT             NULL,
    [I_Curr_Country_ID]          INT             NULL,
    [S_Guardian_Name]            NVARCHAR (MAX)  NULL,
    [I_Guardian_Occupation_ID]   INT             NULL,
    [S_Guardian_Email_ID]        NVARCHAR (MAX)  NULL,
    [S_Guardian_Phone_No]        NVARCHAR (MAX)  NULL,
    [S_Guardian_Mobile_No]       NVARCHAR (MAX)  NULL,
    [I_Income_Group_ID]          INT             NULL,
    [S_Curr_Address1]            NVARCHAR (MAX)  NULL,
    [S_Curr_Address2]            NVARCHAR (MAX)  NULL,
    [S_Curr_Pincode]             NVARCHAR (MAX)  NULL,
    [S_Curr_Area]                NVARCHAR (MAX)  NULL,
    [S_Perm_Address1]            NVARCHAR (MAX)  NULL,
    [S_Perm_Address2]            NVARCHAR (MAX)  NULL,
    [S_Perm_Pincode]             NVARCHAR (MAX)  NULL,
    [I_Perm_City_ID]             INT             NULL,
    [I_Perm_State_ID]            INT             NULL,
    [I_Perm_Country_ID]          INT             NULL,
    [S_Perm_Area]                NVARCHAR (MAX)  NULL,
    [S_Crtd_By]                  NVARCHAR (MAX)  NULL,
    [S_Upd_By]                   NVARCHAR (MAX)  NULL,
    [Dt_Crtd_On]                 DATETIME        NULL,
    [Dt_Upd_On]                  DATETIME        NULL,
    [I_Corporate_ID]             INT             NULL,
    [I_Corporate_Plan_ID]        INT             NULL,
    [I_Caste_ID]                 INT             NULL,
    [S_Student_Photo]            NVARCHAR (MAX)  NULL,
    [I_Residence_Area_ID]        INT             NULL,
    [S_Father_Name]              NVARCHAR (MAX)  NULL,
    [S_Mother_Name]              NVARCHAR (MAX)  NULL,
    [B_IsPreEnquiry]             BIT             NULL,
    [I_Sex_ID]                   INT             NULL,
    [I_Native_Language_ID]       INT             NULL,
    [I_Nationality_ID]           INT             NULL,
    [I_Religion_ID]              INT             NULL,
    [I_Marital_Status_ID]        INT             NULL,
    [I_Blood_Group_ID]           INT             NULL,
    [I_Father_Qualification_ID]  INT             NULL,
    [I_Father_Occupation_ID]     INT             NULL,
    [I_Father_Business_Type_ID]  INT             NULL,
    [S_Father_Company_Name]      NVARCHAR (MAX)  NULL,
    [S_Father_Designation]       NVARCHAR (MAX)  NULL,
    [S_Father_Office_Phone]      NVARCHAR (MAX)  NULL,
    [I_Father_Income_Group_ID]   INT             NULL,
    [S_Father_Photo]             NVARCHAR (MAX)  NULL,
    [S_Father_Office_Address]    NVARCHAR (MAX)  NULL,
    [I_Mother_Qualification_ID]  INT             NULL,
    [I_Mother_Occupation_ID]     INT             NULL,
    [I_Mother_Business_Type_ID]  INT             NULL,
    [S_Mother_Designation]       NVARCHAR (MAX)  NULL,
    [S_Mother_Company_Name]      NVARCHAR (MAX)  NULL,
    [S_Mother_Office_Address]    NVARCHAR (MAX)  NULL,
    [S_Mother_Office_Phone]      NVARCHAR (MAX)  NULL,
    [I_Mother_Income_Group_ID]   INT             NULL,
    [S_Mother_Photo]             NVARCHAR (MAX)  NULL,
    [S_Guardian_Relationship]    NVARCHAR (MAX)  NULL,
    [S_Guardian_Address]         NVARCHAR (MAX)  NULL,
    [I_Monthly_Family_Income_ID] INT             NULL,
    [B_Can_Sponsor_Education]    BIT             NULL,
    [S_Sibling_ID]               NVARCHAR (MAX)  NULL,
    [B_Has_Given_Exam]           BIT             NULL,
    [I_Attempts]                 INT             NULL,
    [S_Other_Institute]          NVARCHAR (MAX)  NULL,
    [N_Duration]                 DECIMAL (18, 2) NULL,
    [I_Seat_Type_ID]             INT             NULL,
    [I_Enrolment_Type_ID]        INT             NULL,
    [S_Enrolment_No]             NVARCHAR (MAX)  NULL,
    [I_Rank_Obtained]            INT             NULL,
    [S_Univ_Registration_No]     NVARCHAR (MAX)  NULL,
    [S_Univ_Roll_No]             NVARCHAR (MAX)  NULL,
    [I_Scholar_Type_ID]          INT             NULL,
    [S_Second_Language_Opted]    NVARCHAR (MAX)  NULL,
    [S_Physical_Ailment]         NVARCHAR (MAX)  NULL,
    [S_Form_No]                  NVARCHAR (MAX)  NULL,
    [B_IsLateral]                BIT             NULL,
    [I_PreEnquiryFor]            INT             NULL,
    [AuditedOn]                  DATETIME        NOT NULL,
    [AuditType]                  CHAR (1)        NOT NULL,
    [AuditId]                    INT             IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_T_Enquiry_Regn_Detail_A] PRIMARY KEY CLUSTERED ([AuditId] ASC)
);

