CREATE TABLE [dbo].[T_ERP_Exam_ScheduleSubjects] (
    [inExamScheduleSubjectId] INT              IDENTITY (1, 1) NOT NULL,
    [unExamScheduleSubjectId] UNIQUEIDENTIFIER CONSTRAINT [DF__T_ERP_Exa__unExa__26BC7A14] DEFAULT (newid()) NULL,
    [inExamScheduleDetailId]  INT              NULL,
    [inClassId]               INT              NULL,
    [inStreamId]              INT              NULL,
    [inSectionId]             INT              NULL,
    [inSubjectTypeID]         INT              NULL,
    [inSubjectID]             INT              NULL,
    [inSubjectComponentID]    INT              NULL,
    [inDisplaySeq]            INT              NULL,
    [inExamMode]              INT              NULL,
    [dcFullMarks]             DECIMAL (18, 2)  NULL,
    [dcMainExamFullMarks]     DECIMAL (18, 2)  NULL,
    [dcInternalFullMarks]     DECIMAL (18, 2)  NULL,
    [dcOrderallPassMarks]     DECIMAL (18, 2)  NULL,
    [isPassMandatory]         BIT              CONSTRAINT [DF__T_ERP_Exa__isPas__27B09E4D] DEFAULT ((0)) NULL,
    [dtStartDate]             DATETIME         NULL,
    [dtEndDate]               DATETIME         NULL,
    [inExamSlotId]            INT              NULL,
    [isDisplayOnApp]          BIT              CONSTRAINT [DF__T_ERP_Exa__isDis__28A4C286] DEFAULT ((0)) NULL,
    [inExamInvigilatorId]     INT              NULL,
    [inExamGraderId]          INT              NULL,
    [inCreatedBy]             INT              NULL,
    [inModifiedBy]            INT              NULL,
    [dtCreatedDate]           DATETIME         NULL,
    [dtModifiedDate]          DATETIME         NULL,
    [inAttendanceStatus]      INT              NULL,
    [dtPublishDate]           DATETIME         NULL,
    [inExamPlatform]          INT              NULL,
    CONSTRAINT [PK__T_ERP_Ex__463DD9D81662E8CD] PRIMARY KEY CLUSTERED ([inExamScheduleSubjectId] ASC)
);

