CREATE TABLE [dbo].[T_ERP_Student_Detail] (
    [I_Student_Detail_ID]       BIGINT         IDENTITY (1, 1) NOT NULL,
    [R_I_Enquiry_Regn_ID]       BIGINT         NULL,
    [S_Student_ID]              NVARCHAR (MAX) NULL,
    [S_Title]                   NVARCHAR (MAX) NULL,
    [S_First_Name]              NVARCHAR (MAX) NULL,
    [S_Middle_Name]             NVARCHAR (MAX) NULL,
    [S_Last_Name]               NVARCHAR (MAX) NULL,
    [Dt_Birth_Date]             DATETIME       NULL,
    [S_Age]                     NVARCHAR (MAX) NULL,
    [S_Email_ID]                NVARCHAR (MAX) NULL,
    [S_Phone_No]                NVARCHAR (MAX) NULL,
    [S_Mobile_No]               NVARCHAR (MAX) NULL,
    [I_Pref_Career_ID]          INT            NULL,
    [S_Curr_Address1]           NVARCHAR (MAX) NULL,
    [S_Curr_Address2]           NVARCHAR (MAX) NULL,
    [I_Curr_Country_ID]         INT            NULL,
    [I_Curr_State_ID]           INT            NULL,
    [I_Curr_City_ID]            INT            NULL,
    [S_Curr_Area]               NVARCHAR (MAX) NULL,
    [S_Curr_Pincode]            NVARCHAR (MAX) NULL,
    [S_Perm_Address1]           NVARCHAR (MAX) NULL,
    [S_Perm_Address2]           NVARCHAR (MAX) NULL,
    [I_Perm_Country_ID]         INT            NULL,
    [I_Perm_State_ID]           INT            NULL,
    [I_Perm_City_ID]            INT            NULL,
    [S_Perm_Area]               NVARCHAR (MAX) NULL,
    [S_Perm_Pincode]            NVARCHAR (MAX) NULL,
    [Is_Active]                 BIT            NOT NULL,
    [I_CreatedBy]               INT            NULL,
    [I_UpdatedBy]               INT            NULL,
    [Dtt_CreatedAt]             DATETIME       CONSTRAINT [DF__T_ERP_Stu__Dtt_C__0180086D] DEFAULT (getdate()) NULL,
    [Dtt_UpdatedAt]             DATETIME       NULL,
    [S_Conduct_Code]            NVARCHAR (MAX) NULL,
    [S_Is_Corporate]            BIT            NULL,
    [I_Corporate_ID]            INT            NULL,
    [I_RollNo]                  INT            NULL,
    [I_Marital_Status_ID]       INT            NULL,
    [I_Transport_ID]            INT            CONSTRAINT [DF_T_Student_Detail_I_Transport_ID_1] DEFAULT ((0)) NULL,
    [I_room_ID]                 INT            CONSTRAINT [DF_T_Student_Detail_I_room_ID_1] DEFAULT ((0)) NULL,
    [I_House_ID]                INT            NULL,
    [I_Route_ID]                INT            NULL,
    [B_Is_APAI_Acc_Settled]     BIT            NULL,
    [Dt_Transport_Deactivation] DATETIME       NULL,
    [B_IsBooking]               INT            CONSTRAINT [Df_Val_1] DEFAULT ((0)) NULL,
    [B_HasTakenLoan]            BIT            NULL,
    [I_DiscountType_ID]         INT            NULL,
    [S_Ext_Email_ID]            NVARCHAR (MAX) NULL,
    [IsDropOut]                 BIT            NULL,
    [IsWaiting]                 BIT            NULL,
    [IsDefaulter]               BIT            NULL,
    [IsOnLeave]                 BIT            NULL,
    [IsCompleted]               BIT            NULL,
    [IsDiscontinued]            BIT            NULL,
    [DefaulterCourses]          NVARCHAR (MAX) NULL,
    [PreDefaulterCourses]       NVARCHAR (MAX) NULL,
    [I_buzzedDB_Slot_ID]        INT            NULL,
    [Student_Status]            INT            NULL,
    CONSTRAINT [PK__T_ERP_St__D352AA7660F4A268] PRIMARY KEY CLUSTERED ([I_Student_Detail_ID] ASC)
);

