CREATE TABLE [dbo].[T_ERP_BankMaster] (
    [ID]                  INT            IDENTITY (1, 1) NOT NULL,
    [stBusinessName]      NVARCHAR (100) NOT NULL,
    [stBusinessType]      NVARCHAR (50)  NULL,
    [stBusinessTypeDesc]  NVARCHAR (MAX) NULL,
    [stBankName]          NVARCHAR (200) NOT NULL,
    [stBranchName]        NVARCHAR (200) NOT NULL,
    [stIFSCCode]          NVARCHAR (20)  NOT NULL,
    [stMICRCode]          NVARCHAR (20)  NULL,
    [stSWIFTCode]         NVARCHAR (20)  NULL,
    [inAccountType]       INT            NOT NULL,
    [stAccountHolderName] NVARCHAR (150) NOT NULL,
    [stAccountNumber]     NVARCHAR (50)  NOT NULL,
    [stBankEmail]         NVARCHAR (100) NULL,
    [stBankPhone]         NVARCHAR (20)  NULL,
    [stSupportingDocs]    NVARCHAR (255) NULL,
    [stKYCDocs]           NVARCHAR (255) NULL,
    [inBankType]          INT            NULL,
    [inStatus]            INT            NOT NULL,
    [stRemarks]           NVARCHAR (MAX) NULL,
    [inBrandID]           INT            NULL,
    [stEmail]             NVARCHAR (100) NULL,
    [stPhone]             NVARCHAR (20)  NULL,
    [stType]              NVARCHAR (20)  NULL,
    [stReferenceId]       NVARCHAR (100) NULL,
    [stContactName]       NVARCHAR (255) NULL,
    [stProfileFields]     NVARCHAR (MAX) NULL,
    [stLegalInfo]         NVARCHAR (MAX) NULL,
    [IsDashboardEnabled]  BIT            NULL,
    [stNotes]             NVARCHAR (MAX) NULL,
    [LinkedAccountId]     NVARCHAR (100) NULL,
    [stPAN]               NVARCHAR (20)  NULL,
    [stGST]               NVARCHAR (20)  NULL,
    [stStreet1]           NVARCHAR (255) NULL,
    [stStreet2]           NVARCHAR (255) NULL,
    [stCity]              NVARCHAR (100) NULL,
    [stState]             NVARCHAR (100) NULL,
    [stPostalCode]        NVARCHAR (20)  NULL,
    [stCountry]           NVARCHAR (100) NULL,
    [stAccountType]       NVARCHAR (100) NULL,
    [stBankType]          NVARCHAR (100) NULL,
    CONSTRAINT [PK_T_ERP_BankMaster] PRIMARY KEY CLUSTERED ([ID] ASC)
);

