CREATE TABLE [dbo].[T_ERP_Exam_SchedulesDetails] (
    [inExamScheduleDetailId]         INT              IDENTITY (1, 1) NOT NULL,
    [unExamScheduleDetailId]         UNIQUEIDENTIFIER CONSTRAINT [DF__T_ERP_Exa__unExa__3D9FDF6C] DEFAULT (newid()) NULL,
    [stExamName]                     NVARCHAR (200)   NULL,
    [inExamTypeId]                   INT              NULL,
    [inExamCategoryId]               INT              NULL,
    [inAcademicSessionId]            INT              NULL,
    [inSchoolProgramId]              INT              NULL,
    [inAdmitCardTemplateId]          INT              NULL,
    [inReportCardTemplateId]         INT              NULL,
    [inMarksEntryStartAfterExamDays] INT              NULL,
    [inMarksEntryCloseDays]          INT              NULL,
    [inGradingSchemeId]              INT              NULL,
    [inExamGradeID]                  INT              NULL,
    [inInternalExamWeightage]        INT              NULL,
    [inMainInternalExamWeightage]    INT              NULL,
    [inTotalWeightage]               INT              NULL,
    [inStatus]                       BIT              CONSTRAINT [DF__T_ERP_Exa__inSta__3E9403A5] DEFAULT ((1)) NULL,
    [inBrandId]                      INT              NULL,
    [inCreatedBy]                    INT              NULL,
    [inModifiedBy]                   INT              NULL,
    [dtCreatedDate]                  DATETIME         NULL,
    [dtModifiedDate]                 DATETIME         NULL,
    [inScheduleStatus]               INT              NULL,
    [inSaveType]                     INT              NULL,
    [inAttendanceStatus]             INT              NULL,
    [inMappingStatus]                INT              CONSTRAINT [DF__T_ERP_Exa__inMap__3B828CD0] DEFAULT ((0)) NULL,
    [inResultProcessStatus]          INT              NULL,
    [dtPublishDate]                  DATETIME         NULL,
    [flgIsFinalExam]                 BIT              DEFAULT ((0)) NULL,
    CONSTRAINT [PK__T_ERP_Ex__012D60C04C686BDD] PRIMARY KEY CLUSTERED ([inExamScheduleDetailId] ASC)
);

