CREATE TABLE [dbo].[T_ERP_Fee_Payment_Installment_Delete_history] (
    [I_Fee_Component_InstallmentID]        BIGINT          NULL,
    [TempInv]                              NVARCHAR (MAX)  NULL,
    [R_I_Enquiry_Regn_ID]                  INT             NULL,
    [I_Stud_Fee_Struct_CompMap_Details_ID] BIGINT          NULL,
    [R_I_Fee_Structure_ID]                 INT             NULL,
    [R_I_Fee_Component_ID]                 INT             NULL,
    [Seq]                                  INT             NULL,
    [Dt_Payment_Installment_Dt]            DATE            NULL,
    [N_Installment_Amount]                 NUMERIC (18, 2) NULL,
    [I_Installment_Status]                 TINYINT         NULL,
    [N_Received_Amt]                       NUMERIC (18, 2) NULL,
    [Adv_Amt]                              NUMERIC (12, 2) NULL,
    [Dt_Payment_Dt]                        DATE            NULL,
    [Is_Active]                            BIT             NULL,
    [Dt_LateFine_Due_Dt]                   DATE            NULL,
    [Dtt_Created_At]                       DATETIME        NULL,
    [Dtt_Modified_At]                      DATETIME        NULL,
    [Is_Cancelled]                         BIT             NULL,
    [Is_Moved]                             BIT             NULL,
    [DT_Moved_Dt]                          DATETIME        NULL,
    [N_CGST_Per]                           NUMERIC (10, 2) NULL,
    [N_SGST_Per]                           NUMERIC (10, 2) NULL,
    [N_IGST_Per]                           NUMERIC (10, 2) NULL,
    [N_CGST_Value]                         NUMERIC (10, 2) NULL,
    [N_SGST_Value]                         NUMERIC (10, 2) NULL,
    [N_IGST_Value]                         NUMERIC (10, 2) NULL,
    [Dt_Deleted_date]                      DATETIME        NULL
);

