CREATE TABLE [dbo].[T_ERP_Exam_ScheduleSubjectDetails] (
    [inExamScheduleSubjectDetailId] INT              IDENTITY (1, 1) NOT NULL,
    [unExamScheduleSubjectDetailId] UNIQUEIDENTIFIER CONSTRAINT [DF__T_ERP_Exa__unExa__65ADD0C6] DEFAULT (newid()) NULL,
    [inExamScheduleDetailId]        INT              NULL,
    [inClassId]                     INT              NULL,
    [stClassName]                   NVARCHAR (100)   NULL,
    [inStreamId]                    INT              NULL,
    [stStreamName]                  NVARCHAR (100)   NULL,
    [inSectionId]                   INT              NULL,
    [stSectionName]                 NVARCHAR (100)   NULL,
    [inSubjectTypeID]               INT              NULL,
    [stSubjectTypeName]             NVARCHAR (200)   NULL,
    [inSubjectID]                   INT              NULL,
    [stSubjectName]                 NVARCHAR (200)   NULL,
    [inSubjectComponentID]          INT              NULL,
    [stSubjectComponentName]        NVARCHAR (200)   NULL,
    [inDisplaySeq]                  INT              NULL,
    [inExamMode]                    INT              NULL,
    [stExamMode]                    NVARCHAR (20)    NULL,
    [dcFullMarks]                   DECIMAL (18, 2)  NULL,
    [dcMainExamFullMarks]           DECIMAL (18, 2)  NULL,
    [dcInternalFullMarks]           DECIMAL (18, 2)  NULL,
    [dcOrderallPassMarks]           DECIMAL (18, 2)  NULL,
    [isPassMandatory]               BIT              CONSTRAINT [DF__T_ERP_Exa__isPas__66A1F4FF] DEFAULT ((0)) NULL,
    [dtStartDate]                   DATETIME         NULL,
    [dtEndDate]                     DATETIME         NULL,
    [inExamSlotId]                  INT              NULL,
    [stExamSlotId]                  NVARCHAR (100)   NULL,
    [isDisplayOnApp]                BIT              CONSTRAINT [DF__T_ERP_Exa__isDis__67961938] DEFAULT ((0)) NULL,
    [inExamInvigilatorId]           INT              NULL,
    [stExamInvigilatorName]         NVARCHAR (200)   NULL,
    [inExamGraderId]                INT              NULL,
    [stExamGraderName]              NVARCHAR (200)   NULL,
    [inCreatedBy]                   INT              NULL,
    [inModifiedBy]                  INT              NULL,
    [dtCreatedDate]                 DATETIME         NULL,
    [dtModifiedDate]                DATETIME         NULL,
    [inAttendanceStatus]            INT              NULL,
    [inMarksStatus]                 INT              CONSTRAINT [DF__T_ERP_Exa__inMar__277B9423] DEFAULT ((1)) NULL,
    [dtPublishDate]                 DATETIME         NULL,
    [inResultPublishStatus]         INT              NULL,
    [inExamPlatform]                INT              NULL,
    [inMappingStatus]               INT              NULL,
    [inResultProcessStatus]         INT              NULL,
    [IsFinalExam]                   BIT              NULL,
    CONSTRAINT [PK__T_ERP_Ex__08120B54541ED477] PRIMARY KEY CLUSTERED ([inExamScheduleSubjectDetailId] ASC)
);

