CREATE TABLE [dbo].[T_ERP_SMS_GPS_Transport_SYNCLog] (
    [Old_RouteID]             INT             NULL,
    [Old_RouteName]           NVARCHAR (MAX)  NULL,
    [Old_PickupID]            INT             NULL,
    [Old_PickupLocation_Name] NVARCHAR (MAX)  NULL,
    [Old_Landmark]            NVARCHAR (MAX)  NULL,
    [Old_FullAddress]         NVARCHAR (MAX)  NULL,
    [Old_Monthly_Fee]         DECIMAL (10, 2) NULL,
    [New_RouteID]             INT             NULL,
    [New_RouteName]           NVARCHAR (MAX)  NULL,
    [New_PickupID]            INT             NULL,
    [New_PickupLocation_Name] NVARCHAR (MAX)  NULL,
    [New_Monthly_Fee]         DECIMAL (10, 2) NULL,
    [Is_Upadted_FromBuzz]     BIT             NULL,
    [dt_CreateDt]             DATETIME        CONSTRAINT [DF__T_ERP_SMS__dt_Cr__02B423C8] DEFAULT (getdate()) NULL,
    [dt_UpdateDt]             DATETIME        NULL,
    [Old_StartLocation]       NVARCHAR (MAX)  NULL,
    [New_StartLocation]       NVARCHAR (MAX)  NULL,
    [Old_DropOrder]           INT             NULL,
    [I_BrandID]               INT             NULL,
    [New_PickupOrder]         INT             NULL,
    [is_synced]               BIT             CONSTRAINT [DF__T_ERP_SMS__is_sy__5794BB99] DEFAULT ((0)) NULL,
    [New_Landmark]            NVARCHAR (MAX)  NULL,
    [New_FullAddress]         NVARCHAR (MAX)  NULL,
    [New_DropOrder]           INT             NULL,
    [Dt_create_dt]            DATETIME        CONSTRAINT [DF__T_ERP_SMS__Dt_cr__770D66F2] DEFAULT (getdate()) NULL,
    [row_id]                  INT             IDENTITY (1, 1) NOT NULL,
    [erp_pickupid]            INT             NULL,
    [buzzed_pickupid]         INT             NULL,
    [dt_modify_dt]            DATETIME        NULL
);

