CREATE TABLE [dbo].[T_ERP_Stud_Fee_Struct_Comp_Mapping_Details] (
    [I_Stud_Fee_Struct_CompMap_Details_ID] BIGINT          IDENTITY (1, 1) NOT NULL,
    [R_I_Stud_Fee_Struct_CompMap_ID]       BIGINT          NULL,
    [R_I_Fee_Structure_ID]                 INT             NULL,
    [R_I_Fee_Component_ID]                 INT             NULL,
    [Seq]                                  INT             NULL,
    [N_Component_Actual_Amount]            NUMERIC (12, 2) NULL,
    [Dtt_Created_At]                       DATETIME        CONSTRAINT [DF__T_ERP_Stu__Dtt_C__37DC191E] DEFAULT (getdate()) NULL,
    [Dtt_Modified_At]                      DATETIME        NULL,
    [I_Created_By]                         INT             NULL,
    [I_Modified_By]                        INT             NULL,
    [Is_Active]                            BIT             CONSTRAINT [DF__T_ERP_Stu__Is_Ac__38D03D57] DEFAULT ((1)) NULL,
    [R_I_Fee_Pay_Installment_ID]           INT             NULL,
    [Dt_Moved_DT]                          DATETIME        NULL,
    [Is_Moved]                             BIT             NULL,
    [I_ExtracomponentRef_ID]               INT             NULL,
    [I_ExtracomponentRef_Type]             INT             NULL,
    [CGST_per]                             NUMERIC (10, 2) NULL,
    [SGST_per]                             NUMERIC (10, 2) NULL,
    [IGST_per]                             NUMERIC (10, 2) NULL,
    [IGST_value]                           NUMERIC (10, 2) NULL,
    [CGST_value]                           NUMERIC (10, 2) NULL,
    [SGST_value]                           NUMERIC (10, 2) NULL,
    [I_ExtracomponentRef2_ID]              INT             NULL,
    [Is_OneTime]                           BIT             NULL,
    [StartPeriod]                          INT             NULL,
    [I_Brand_ID]                           INT             NULL,
    CONSTRAINT [PK__T_ERP_St__343A9E3CC82A7C84] PRIMARY KEY CLUSTERED ([I_Stud_Fee_Struct_CompMap_Details_ID] ASC)
);

