CREATE TABLE [dbo].[T_ERP_Transaction_Master] (
    [I_ERP_Transaction_Master_ID]       INT            IDENTITY (1, 1) NOT NULL,
    [S_Mobile_No]                       NVARCHAR (MAX) NULL,
    [I_ERP_TransactionNo]               NVARCHAR (MAX) NULL,
    [I_BrandID]                         INT            NULL,
    [I_CentreID]                        INT            NULL,
    [I_StudentDetailID]                 INT            NOT NULL,
    [Dt_TransactionDate]                DATETIME       NOT NULL,
    [S_TransactionSource]               NVARCHAR (MAX) NOT NULL,
    [I_ERP_Brand_PaymentGateway_Map_id] INT            NOT NULL,
    [S_TransactionMode]                 NVARCHAR (MAX) NULL,
    [S_TransactionStatus]               NVARCHAR (MAX) NOT NULL,
    [I_TransactionTotalAmount]          DECIMAL (8, 2) NOT NULL,
    [CanBeProcessed]                    BIT            NULL,
    [IsCompleted]                       BIT            NULL,
    [Dt_CreatedOn]                      DATETIME       NOT NULL,
    [I_CreatedBy]                       INT            NOT NULL,
    [Dt_UpdatedOn]                      DATETIME       NULL,
    [I_UpdatedBy]                       INT            NULL,
    [Dt_CompletedOn]                    DATETIME       NULL,
    [I_StatusID]                        INT            NULL,
    [PaymentDetailsXML]                 XML            NULL,
    [PaymentJson]                       NVARCHAR (MAX) NULL,
    [SMSPaymentMode]                    INT            NULL,
    [SuccessXML]                        XML            NULL,
    [PG_History_ID]                     INT            NULL,
    [Order_ID]                          NVARCHAR (MAX) NULL,
    [RequestLogID]                      INT            NULL
);

