CREATE TABLE [dbo].[T_ERP_Student_DataMapped] (
    [ID]                      BIGINT         IDENTITY (1, 1) NOT NULL,
    [I_Brand_ID]              INT            NULL,
    [I_Student_Detail_ID]     INT            NULL,
    [student_erp_id]          NVARCHAR (MAX) NULL,
    [S_Course_Name]           NVARCHAR (MAX) NULL,
    [S_Batch_Name]            NVARCHAR (MAX) NULL,
    [StudentName]             NVARCHAR (MAX) NULL,
    [S_Mobile_No]             NVARCHAR (MAX) NULL,
    [S_Class_Name]            NVARCHAR (MAX) NULL,
    [S_Section_Name]          NVARCHAR (MAX) NULL,
    [S_Stream]                NVARCHAR (MAX) NULL,
    [S_School_Group_Code]     NVARCHAR (MAX) NULL,
    [Section_Name_GPS]        NVARCHAR (MAX) NULL,
    [S_PickupPoint_Name]      NVARCHAR (MAX) NULL,
    [N_Fees]                  INT            NULL,
    [S_Route_No]              NVARCHAR (MAX) NULL,
    [FatherName]              NVARCHAR (MAX) NULL,
    [Father_Parent_Master_ID] INT            NULL,
    [FatherContactNumber]     NVARCHAR (MAX) NULL,
    [Father_Is_Primary]       NVARCHAR (MAX) NULL,
    [F_Is_BusTravel]          NVARCHAR (MAX) NULL,
    [Mothername]              NVARCHAR (MAX) NULL,
    [Mother_Parent_Master_ID] INT            NULL,
    [MotherContactNumber]     NVARCHAR (MAX) NULL,
    [Mother_Is_Primary]       NVARCHAR (MAX) NULL,
    [M_Is_BusTravel]          NVARCHAR (MAX) NULL,
    [Dt_CreateDate]           DATETIME       DEFAULT (getdate()) NULL,
    [Dt_Modify_Dt]            DATETIME       DEFAULT (getdate()) NULL,
    [Is_Fetch]                BIT            NULL
);

