CREATE TABLE [dbo].[T_ERP_Fee_Payment_Installment] (
    [I_Fee_Component_InstallmentID]        BIGINT          IDENTITY (1, 1) NOT NULL,
    [TempInv]                              NVARCHAR (MAX)  NULL,
    [R_I_Enquiry_Regn_ID]                  INT             NULL,
    [I_Stud_Fee_Struct_CompMap_Details_ID] BIGINT          NULL,
    [R_I_Fee_Structure_ID]                 INT             NULL,
    [R_I_Fee_Component_ID]                 INT             NULL,
    [Seq]                                  INT             NULL,
    [Dt_Payment_Installment_Dt]            DATE            NULL,
    [N_Installment_Amount]                 NUMERIC (18, 2) NULL,
    [I_Installment_Status]                 TINYINT         NULL,
    [N_Received_Amt]                       NUMERIC (18, 2) NULL,
    [Adv_Amt]                              NUMERIC (12, 2) NULL,
    [Dt_Payment_Dt]                        DATE            NULL,
    [Is_Active]                            BIT             CONSTRAINT [DF__T_ERP_Fee__Is_Ac__40715F1F] DEFAULT ((1)) NULL,
    [Dt_LateFine_Due_Dt]                   DATE            NULL,
    [Dtt_Created_At]                       DATETIME        CONSTRAINT [DF__T_ERP_Fee__Dtt_C__481280E7] DEFAULT (getdate()) NULL,
    [Dtt_Modified_At]                      DATETIME        NULL,
    [Is_Cancelled]                         BIT             CONSTRAINT [DF__T_ERP_Fee__Is_Ca__556C7C05] DEFAULT ((0)) NULL,
    [Is_Moved]                             BIT             NULL,
    [DT_Moved_Dt]                          DATETIME        NULL,
    [N_CGST_Per]                           NUMERIC (10, 2) NULL,
    [N_SGST_Per]                           NUMERIC (10, 2) NULL,
    [N_IGST_Per]                           NUMERIC (10, 2) NULL,
    [N_CGST_Value]                         NUMERIC (10, 2) NULL,
    [N_SGST_Value]                         NUMERIC (10, 2) NULL,
    [N_IGST_Value]                         NUMERIC (10, 2) NULL,
    [I_Brand_ID]                           INT             NULL,
    CONSTRAINT [PK__T_ERP_Fe__B3450CFA023C0D1B] PRIMARY KEY CLUSTERED ([I_Fee_Component_InstallmentID] ASC)
);

