CREATE TABLE [dbo].[T_Fee_Component_Master] (
    [I_Fee_Component_ID]        INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [S_Component_Code]          NVARCHAR (MAX) NULL,
    [S_Component_Name]          NVARCHAR (MAX) NULL,
    [I_Status]                  INT            NULL,
    [S_Crtd_By]                 NVARCHAR (MAX) NULL,
    [S_Upd_By]                  NVARCHAR (MAX) NULL,
    [Dt_Crtd_On]                DATETIME       NULL,
    [Dt_Upd_On]                 DATETIME       NULL,
    [Is_Discount_Applicable]    INT            NULL,
    [Is_Invoice_Receipt]        INT            NULL,
    [I_Fee_Component_Type_ID]   INT            NULL,
    [I_Brand_ID]                INT            NULL,
    [S_FeeComponentForSMS]      NVARCHAR (MAX) NULL,
    [S_Type_Of_Component]       NVARCHAR (MAX) NULL,
    [Is_individual]             BIT            NULL,
    [I_Extracomponent_Ref_Type] INT            NULL,
    [Is_GST_Applicable]         BIT            NULL,
    [Is_Display_Others]         BIT            NULL,
    [I_Bank_ID]                 INT            NULL,
    [BankEffectiveFrom]         DATETIME       NULL,
    [BankEffectiveTo]           DATETIME       NULL,
    [S_Individual_Comp_Type]    CHAR (1)       NULL,
    CONSTRAINT [PK__T_Fee_Component___0C86A9A4] PRIMARY KEY CLUSTERED ([I_Fee_Component_ID] ASC)
);

