CREATE TABLE [dbo].[T_SMS_REFERENCE_TYPE_MASTER] (
    [I_REFERENCE_TYPE_ID]   INT            IDENTITY (1, 1) NOT NULL,
    [S_REFERENCE_TYPE_NAME] NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_T_SMS_REFERENCE_TYPE_MASTER] PRIMARY KEY CLUSTERED ([I_REFERENCE_TYPE_ID] ASC)
);

