CREATE TABLE [dbo].[T_SMS_PARAM_MASTER] (
    [I_PARAM_ID]    INT            IDENTITY (1, 1) NOT NULL,
    [S_PARAM_NAME]  NVARCHAR (MAX) NOT NULL,
    [S_PARAM_VALUE] NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_T_SMS_PARAM_MASTER] PRIMARY KEY CLUSTERED ([I_PARAM_ID] ASC)
);

