CREATE TABLE [dbo].[zz_razorpay_transaction] (
    [entity_id]      NVARCHAR (255) NULL,
    [type]           NVARCHAR (255) NULL,
    [debit]          FLOAT (53)     NULL,
    [credit]         FLOAT (53)     NULL,
    [amount]         FLOAT (53)     NULL,
    [currency]       NVARCHAR (255) NULL,
    [fee]            FLOAT (53)     NULL,
    [tax]            FLOAT (53)     NULL,
    [on_hold]        FLOAT (53)     NULL,
    [settled]        FLOAT (53)     NULL,
    [created_at]     DATETIME       NULL,
    [settled_at]     DATETIME       NULL,
    [settlement_id]  NVARCHAR (255) NULL,
    [description]    NVARCHAR (255) NULL,
    [notes]          NVARCHAR (255) NULL,
    [payment_id]     NVARCHAR (255) NULL,
    [arn]            NVARCHAR (255) NULL,
    [settlement_utr] NVARCHAR (255) NULL,
    [order_id]       NVARCHAR (255) NULL,
    [order_receipt]  NVARCHAR (255) NULL,
    [method]         NVARCHAR (255) NULL,
    [upi_flow]       NVARCHAR (255) NULL,
    [card_network]   NVARCHAR (255) NULL,
    [card_issuer]    NVARCHAR (255) NULL,
    [card_type]      NVARCHAR (255) NULL,
    [dispute_id]     NVARCHAR (255) NULL,
    [additional_utr] NVARCHAR (255) NULL
);

