CREATE TABLE [PLACEMENT].[T_Placement_Registration] (
    [I_Job_Type_ID]              INT            NULL,
    [I_Country_ID]               INT            NULL,
    [I_Centre_ID]                INT            NULL,
    [I_Brand_ID]                 INT            NULL,
    [I_Student_Detail_ID]        INT            NOT NULL,
    [I_Enroll_No]                INT            NULL,
    [S_Preferred_Location]       VARCHAR (2000) NULL,
    [S_Job_Preference]           VARCHAR (2000) NULL,
    [Dt_Actual_Course_Comp_Date] DATETIME       NULL,
    [I_Document_ID]              INT            NULL,
    [S_Height]                   VARCHAR (20)   NULL,
    [S_Weight]                   VARCHAR (20)   NULL,
    [S_Age]                      VARCHAR (20)   NULL,
    [S_Crtd_By]                  VARCHAR (20)   NULL,
    [I_Acknowledgement_Count]    INT            NULL,
    [S_Upd_By]                   VARCHAR (20)   NULL,
    [Dt_Crtd_On]                 DATETIME       NULL,
    [Dt_Upd_On]                  DATETIME       NULL,
    [Dt_Expec_Course_Comp_Date]  DATETIME       NULL,
    [S_Cell_No]                  VARCHAR (50)   NULL,
    [S_Current_Organization]     VARCHAR (50)   NULL,
    [S_Designation]              VARCHAR (20)   NULL,
    [I_Status]                   INT            NOT NULL,
    [B_Profile_Viewed]           BIT            NULL,
    [B_Placement_Asistance]      BIT            NULL,
    CONSTRAINT [PK__T_Placement_Regi__31D829E4] PRIMARY KEY CLUSTERED ([I_Student_Detail_ID] ASC)
);

