CREATE TABLE [PLACEMENT].[T_Vacancy_Detail] (
    [I_Vacancy_ID]          INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [I_Employer_ID]         INT            NULL,
    [S_Min_Height]          VARCHAR (20)   NULL,
    [S_Max_Height]          VARCHAR (20)   NULL,
    [S_Min_Weight]          VARCHAR (20)   NULL,
    [S_Height_UOM]          VARCHAR (10)   NULL,
    [S_Max_Weight]          VARCHAR (20)   NULL,
    [C_Gender]              CHAR (1)       NULL,
    [I_No_Of_Openings]      INT            NULL,
    [S_Weight_UOM]          VARCHAR (10)   NULL,
    [S_Job_Type]            VARCHAR (50)   NULL,
    [S_Pay_Scale]           VARCHAR (50)   NULL,
    [S_Vacancy_Description] VARCHAR (1000) NULL,
    [S_Remarks]             VARCHAR (1000) NULL,
    [S_Crtd_By]             VARCHAR (20)   NULL,
    [S_Upd_By]              VARCHAR (20)   NULL,
    [Dt_Crtd_On]            DATETIME       NULL,
    [Dt_Upd_On]             DATETIME       NOT NULL,
    [B_Transport]           BIT            NOT NULL,
    [S_Role_Designation]    VARCHAR (50)   NULL,
    [Dt_Date_Of_Interview]  DATETIME       NULL,
    [I_Nature_Of_Business]  INT            NULL,
    [B_Fresher_Allowed]     BIT            NOT NULL,
    [S_Work_Experience]     VARCHAR (200)  NULL,
    [B_Shift]               BIT            NOT NULL,
    [I_Status]              INT            NOT NULL,
    CONSTRAINT [PK__T_Vacancy_Detail__172433A8] PRIMARY KEY CLUSTERED ([I_Vacancy_ID] ASC)
);

