CREATE PROC [dbo].[uspDeleteStudentFromPortal]
(
@I_ENQUIRY_REGN_ID INT
)
 
AS 
BEGIN
SET NOCOUNT ON
SET XACT_ABORT ON
BEGIN TRY
BEGIN TRANSACTION

DECLARE @CENTERID INT
DECLARE @I_STUDENT_DETAIL_ID INT

SELECT @CENTERID=I_CENTRE_ID FROM T_ENQUIRY_REGN_DETAIL 
WHERE I_ENQUIRY_REGN_ID=@I_ENQUIRY_REGN_ID

DECLARE _CURSOR CURSOR FOR
	SELECT DISTINCT I_STUDENT_DETAIL_ID FROM T_STUDENT_DETAIL WHERE I_ENQUIRY_REGN_ID IN
	(SELECT I_ENQUIRY_REGN_ID FROM T_ENQUIRY_REGN_DETAIL WHERE I_CENTRE_ID =@CENTERID AND I_ENQUIRY_REGN_ID=@I_ENQUIRY_REGN_ID)

		OPEN _CURSOR
		FETCH NEXT FROM _CURSOR INTO @I_STUDENT_DETAIL_ID

		WHILE @@FETCH_STATUS = 0
		BEGIN

		DELETE FROM T_RECEIPT_TAX_DETAIL
		WHERE I_RECEIPT_COMP_DETAIL_ID IN 
		(	
			SELECT RCD.I_RECEIPT_COMP_DETAIL_ID
			FROM T_RECEIPT_COMPONENT_DETAIL RCD
			INNER JOIN T_RECEIPT_HEADER RH
			ON RCD.I_RECEIPT_DETAIL_ID = RH.I_RECEIPT_HEADER_ID
			AND RH.I_ENQUIRY_REGN_ID=@I_ENQUIRY_REGN_ID	
			UNION
			SELECT I_RECEIPT_COMP_DETAIL_ID FROM T_RECEIPT_COMPONENT_DETAIL 
			WHERE I_RECEIPT_DETAIL_ID IN 
				(	SELECT I_RECEIPT_HEADER_ID FROM T_RECEIPT_HEADER 
					WHERE I_STUDENT_DETAIL_ID=@I_STUDENT_DETAIL_ID
				)
		)
	
		DELETE FROM T_RECEIPT_COMPONENT_DETAIL
		WHERE I_RECEIPT_DETAIL_ID IN (	SELECT I_RECEIPT_HEADER_ID
										FROM T_RECEIPT_HEADER 
										WHERE I_ENQUIRY_REGN_ID=@I_ENQUIRY_REGN_ID)

		DELETE FROM T_RECEIPT_COMPONENT_DETAIL
		WHERE I_INVOICE_DETAIL_ID IN	(	
									SELECT I_INVOICE_DETAIL_ID 
									FROM T_INVOICE_CHILD_DETAIL
									WHERE I_INVOICE_CHILD_HEADER_ID IN
									(	
										SELECT I_INVOICE_CHILD_HEADER_ID 
										FROM T_INVOICE_CHILD_HEADER
										WHERE I_INVOICE_HEADER_ID IN 
										(	
											SELECT I_INVOICE_HEADER_ID 
											FROM T_INVOICE_PARENT
											WHERE I_STUDENT_DETAIL_ID=@I_STUDENT_DETAIL_ID
										)
									)	
								)
								

		DELETE FROM T_ONACCOUNT_RECEIPT_TAX
		WHERE I_RECEIPT_HEADER_ID IN (	SELECT I_RECEIPT_HEADER_ID
										FROM T_RECEIPT_HEADER 
										WHERE I_ENQUIRY_REGN_ID=@I_ENQUIRY_REGN_ID)

		DELETE FROM dbo.T_RECEIPT_HEADER WHERE I_ENQUIRY_REGN_ID=@I_ENQUIRY_REGN_ID

		DELETE FROM dbo.T_RECEIPT_HEADER WHERE I_STUDENT_DETAIL_ID=@I_STUDENT_DETAIL_ID

		DELETE FROM T_INVOICE_DETAIL_TAX 
		WHERE I_INVOICE_DETAIL_ID IN (	SELECT ICD.I_INVOICE_DETAIL_ID
										FROM T_INVOICE_CHILD_DETAIL ICD
										INNER JOIN T_INVOICE_CHILD_HEADER ICH
										ON ICD.I_INVOICE_CHILD_HEADER_ID = ICH.I_INVOICE_CHILD_HEADER_ID
										INNER JOIN T_INVOICE_PARENT IP
										ON ICH.I_INVOICE_HEADER_ID = IP.I_INVOICE_HEADER_ID
										AND IP.I_CENTRE_ID = @CENTERID	AND 
										ICD.I_INVOICE_DETAIL_ID IN	(	
																	SELECT I_INVOICE_DETAIL_ID 
																	FROM T_INVOICE_CHILD_DETAIL
																	WHERE I_INVOICE_CHILD_HEADER_ID IN
																	(	
																		SELECT I_INVOICE_CHILD_HEADER_ID 
																		FROM T_INVOICE_CHILD_HEADER
																		WHERE I_INVOICE_HEADER_ID IN 
																		(	
																			SELECT I_INVOICE_HEADER_ID 
																			FROM T_INVOICE_PARENT
																			WHERE I_STUDENT_DETAIL_ID=@I_STUDENT_DETAIL_ID
																		)
																	)	
																)
											) 
									

		DELETE FROM T_INVOICE_CHILD_DETAIL 
		WHERE I_INVOICE_CHILD_HEADER_ID IN (	SELECT ICH.I_INVOICE_CHILD_HEADER_ID
												FROM T_INVOICE_CHILD_HEADER ICH
												INNER JOIN T_INVOICE_PARENT IP
												ON ICH.I_INVOICE_HEADER_ID = IP.I_INVOICE_HEADER_ID
												AND IP.I_CENTRE_ID = @CENTERID AND ICH.I_INVOICE_HEADER_ID IN 
																				(	
																					SELECT I_INVOICE_HEADER_ID 
																					FROM T_INVOICE_PARENT
																					WHERE I_STUDENT_DETAIL_ID=@I_STUDENT_DETAIL_ID
																				)
											)  	
		
		DELETE FROM T_INVOICE_CHILD_HEADER
		WHERE I_INVOICE_HEADER_ID IN (	SELECT I_INVOICE_HEADER_ID
										FROM T_INVOICE_PARENT 
										WHERE I_CENTRE_ID = @CENTERID	AND I_INVOICE_HEADER_ID IN 
																		(	
																			SELECT I_INVOICE_HEADER_ID 
																			FROM T_INVOICE_PARENT
																			WHERE I_STUDENT_DETAIL_ID=@I_STUDENT_DETAIL_ID
																		)
									)

		DELETE FROM T_INVOICE_PARENT WHERE I_CENTRE_ID = @CENTERID AND I_STUDENT_DETAIL_ID=@I_STUDENT_DETAIL_ID
			
		SELECT I_STUDENT_DETAIL_ID INTO #TEMP_STUDENT1 FROM T_STUDENT_DETAIL WHERE I_ENQUIRY_REGN_ID=@I_ENQUIRY_REGN_ID

		-- DELETE STUDENT MODULE MAP
		DELETE FROM T_STUDENT_MODULE_DETAIL
		WHERE I_STUDENT_DETAIL_ID IN (	SELECT I_STUDENT_DETAIL_ID FROM #TEMP_STUDENT1	)

		-- DELETE STUDENT TERM MAP
		DELETE FROM T_STUDENT_TERM_DETAIL
		WHERE I_STUDENT_DETAIL_ID IN (	SELECT I_STUDENT_DETAIL_ID FROM #TEMP_STUDENT1	)
		
		-- DELETE STUDENT COURSE MAP
		DELETE FROM T_STUDENT_COURSE_DETAIL
		WHERE I_STUDENT_DETAIL_ID IN (	SELECT I_STUDENT_DETAIL_ID FROM #TEMP_STUDENT1	)

		-- DELETE STUDENT LEAVE MAP
		DELETE FROM T_STUDENT_LEAVE_REQUEST_AUDIT 
		WHERE I_STUDENT_DETAIL_ID IN (	SELECT I_STUDENT_DETAIL_ID FROM #TEMP_STUDENT1	)

		DELETE FROM T_STUDENT_LEAVE_REQUEST 
		WHERE I_STUDENT_DETAIL_ID IN (	SELECT I_STUDENT_DETAIL_ID FROM #TEMP_STUDENT1	)

		-- DELETE STUDENT DROPOUT 	
		DELETE FROM ACADEMICS.T_DROPOUT_DETAILS 
		WHERE I_STUDENT_DETAIL_ID IN (	SELECT I_STUDENT_DETAIL_ID FROM #TEMP_STUDENT1	)
		
		DELETE FROM ACADEMICS.T_DROPOUT_DETAILS 
		WHERE I_STUDENT_DETAIL_ID IN (	SELECT I_STUDENT_DETAIL_ID FROM #TEMP_STUDENT1	)
		
		--NEW ADD--

		DELETE FROM ACADEMICS.T_DROPOUT_DTLS_AUDIT 
		WHERE I_STUDENT_ID IN (	SELECT I_STUDENT_DETAIL_ID FROM #TEMP_STUDENT1	)
			
		-- DELETE STUDENT HIERARCHY MAP
		DELETE FROM T_USER_HIERARCHY_DETAILS
		WHERE I_USER_ID IN (	SELECT I_USER_ID
								FROM T_USER_MASTER 
								WHERE I_REFERENCE_ID IN (	SELECT I_STUDENT_DETAIL_ID FROM #TEMP_STUDENT1	)
								AND S_USER_TYPE = 'ST'	)

		-- DELETE STUDENT ROLE MAP
		DELETE FROM T_USER_ROLE_DETAILS
		WHERE I_USER_ID IN (	SELECT I_USER_ID
								FROM T_USER_MASTER 
								WHERE I_REFERENCE_ID IN (	SELECT I_STUDENT_DETAIL_ID FROM #TEMP_STUDENT1	)
								AND S_USER_TYPE = 'ST'	)

		DELETE FROM DBO.T_USER_AUDIT_TRAIL
		WHERE I_USER_ID IN (	SELECT I_USER_ID
								FROM T_USER_MASTER 
								WHERE I_REFERENCE_ID IN (	SELECT I_STUDENT_DETAIL_ID FROM #TEMP_STUDENT1	)
								AND S_USER_TYPE = 'ST'	)
								
		-- DELETE LOGIN TRAIL
		DELETE FROM T_LOGIN_TRAIL
		WHERE I_USER_ID IN (	SELECT I_USER_ID
								FROM T_USER_MASTER 
								WHERE I_REFERENCE_ID IN (	SELECT I_STUDENT_DETAIL_ID FROM #TEMP_STUDENT1	)
								AND S_USER_TYPE = 'ST'	) 						

		-- DELETE USER DATA
		DELETE FROM T_USER_MASTER
		WHERE I_USER_ID IN (	SELECT I_USER_ID
								FROM T_USER_MASTER 
								WHERE I_REFERENCE_ID IN (	SELECT I_STUDENT_DETAIL_ID FROM #TEMP_STUDENT1	)
								AND S_USER_TYPE = 'ST'	)

		-- DELETE STUDENT MARKS
		DELETE FROM EXAMINATION.T_STUDENT_MARKS 
		WHERE I_STUDENT_DETAIL_ID IN (	SELECT I_STUDENT_DETAIL_ID FROM #TEMP_STUDENT1	)

		-- DELETE STUDENT ATTENDANCE
		DELETE FROM T_STUDENT_ATTENDANCE_DETAILS 
		WHERE I_STUDENT_DETAIL_ID IN (	SELECT I_STUDENT_DETAIL_ID FROM #TEMP_STUDENT1 )


		-- DELETE STUDENT CENTER DETAILS
		DELETE FROM T_STUDENT_CENTER_DETAIL WHERE I_STUDENT_DETAIL_ID IN ( SELECT I_STUDENT_DETAIL_ID FROM #TEMP_STUDENT1 )

		-- DELETE STUDENT MASTER
		
		DELETE FROM EXAMINATION.T_Eligibility_List WHERE I_STUDENT_DETAIL_ID IN ( SELECT I_STUDENT_DETAIL_ID FROM #TEMP_STUDENT1 )

		DROP TABLE #TEMP_STUDENT1

			FETCH NEXT FROM _CURSOR INTO @I_STUDENT_DETAIL_ID
		END	
	
	CLOSE _CURSOR
	DEALLOCATE _CURSOR


		--COMMENTED ABOVE AND ADDED BELOW--
		DELETE FROM T_STUDENT_DETAIL WHERE I_ENQUIRY_REGN_ID IN (@I_ENQUIRY_REGN_ID)
		
		DELETE FROM dbo.T_Enquiry_Regn_Followup WHERE I_ENQUIRY_REGN_ID IN (@I_ENQUIRY_REGN_ID)
		
		DELETE FROM T_Enquiry_Course 
		WHERE I_ENQUIRY_REGN_ID IN (@I_ENQUIRY_REGN_ID	)
			
		-- DELETE STUDENT ENQUIRY DETAILS
		DELETE FROM T_ENQUIRY_REGN_DETAIL 
		WHERE I_ENQUIRY_REGN_ID IN (@I_ENQUIRY_REGN_ID	)
			
		


COMMIT TRANSACTION
END TRY
BEGIN CATCH
SELECT ERROR_MESSAGE(),ERROR_SEVERITY()
ROLLBACK TRANSACTION
END CATCH
END
