CREATE PROC [dbo].[uspDeleteStudentInvoiceReceipt] 
(
@I_STUDENT_DETAIL_ID INT
)

AS 
BEGIN
SET NOCOUNT ON
SET XACT_ABORT ON
BEGIN TRY
BEGIN TRANSACTION

		DELETE FROM T_RECEIPT_TAX_DETAIL
		WHERE I_RECEIPT_COMP_DETAIL_ID IN 
		(	
			SELECT I_RECEIPT_COMP_DETAIL_ID FROM T_RECEIPT_COMPONENT_DETAIL 
			WHERE I_RECEIPT_DETAIL_ID IN 
				(	SELECT I_RECEIPT_HEADER_ID FROM T_RECEIPT_HEADER 
					WHERE I_STUDENT_DETAIL_ID=@I_STUDENT_DETAIL_ID
				)
		)
	
		DELETE FROM T_RECEIPT_COMPONENT_DETAIL 
			WHERE I_RECEIPT_DETAIL_ID IN 
				(	SELECT I_RECEIPT_HEADER_ID FROM T_RECEIPT_HEADER 
					WHERE I_STUDENT_DETAIL_ID=@I_STUDENT_DETAIL_ID
				)
								

		DELETE FROM T_ONACCOUNT_RECEIPT_TAX
		WHERE I_RECEIPT_HEADER_ID IN (	SELECT I_RECEIPT_HEADER_ID FROM T_RECEIPT_HEADER 
					WHERE I_STUDENT_DETAIL_ID=@I_STUDENT_DETAIL_ID)

		DELETE FROM T_RECEIPT_HEADER WHERE I_STUDENT_DETAIL_ID=@I_STUDENT_DETAIL_ID

		DELETE FROM T_INVOICE_DETAIL_TAX 
		WHERE I_INVOICE_DETAIL_ID IN (	SELECT ICD.I_INVOICE_DETAIL_ID
										FROM T_INVOICE_CHILD_DETAIL ICD
										INNER JOIN T_INVOICE_CHILD_HEADER ICH
										ON ICD.I_INVOICE_CHILD_HEADER_ID = ICH.I_INVOICE_CHILD_HEADER_ID
										INNER JOIN T_INVOICE_PARENT IP
										ON ICH.I_INVOICE_HEADER_ID = IP.I_INVOICE_HEADER_ID
										where IP.I_STUDENT_DETAIL_ID=@I_STUDENT_DETAIL_ID
										)
									

		DELETE FROM T_INVOICE_CHILD_DETAIL 
		WHERE I_INVOICE_CHILD_HEADER_ID IN (	SELECT ICH.I_INVOICE_CHILD_HEADER_ID
												FROM T_INVOICE_CHILD_HEADER ICH
												INNER JOIN T_INVOICE_PARENT IP
												ON ICH.I_INVOICE_HEADER_ID = IP.I_INVOICE_HEADER_ID
												AND ICH.I_INVOICE_HEADER_ID IN 
																				(	
																					SELECT I_INVOICE_HEADER_ID 
																					FROM T_INVOICE_PARENT
																					WHERE I_STUDENT_DETAIL_ID=@I_STUDENT_DETAIL_ID
																				)
											)  	
		
		DELETE FROM T_INVOICE_CHILD_HEADER
		WHERE I_INVOICE_HEADER_ID IN (	SELECT I_INVOICE_HEADER_ID
										FROM T_INVOICE_PARENT 
										WHERE I_INVOICE_HEADER_ID IN 
											(	
												SELECT I_INVOICE_HEADER_ID 
												FROM T_INVOICE_PARENT
												WHERE I_STUDENT_DETAIL_ID=@I_STUDENT_DETAIL_ID
											)
									)

		DELETE FROM T_INVOICE_PARENT WHERE I_STUDENT_DETAIL_ID=@I_STUDENT_DETAIL_ID
			

		-- DELETE STUDENT MODULE MAP
		DELETE FROM T_STUDENT_MODULE_DETAIL
		WHERE I_STUDENT_DETAIL_ID = @I_STUDENT_DETAIL_ID

		-- DELETE STUDENT TERM MAP
		DELETE FROM T_STUDENT_TERM_DETAIL
		WHERE I_STUDENT_DETAIL_ID = @I_STUDENT_DETAIL_ID
		
		-- DELETE STUDENT COURSE MAP
		DELETE FROM T_STUDENT_COURSE_DETAIL
		WHERE I_STUDENT_DETAIL_ID = @I_STUDENT_DETAIL_ID

		-- DELETE STUDENT LEAVE MAP
		DELETE FROM T_STUDENT_LEAVE_REQUEST_AUDIT 
		WHERE I_STUDENT_DETAIL_ID = @I_STUDENT_DETAIL_ID

		DELETE FROM T_STUDENT_LEAVE_REQUEST 
		WHERE I_STUDENT_DETAIL_ID = @I_STUDENT_DETAIL_ID

		-- DELETE STUDENT DROPOUT 	
		DELETE FROM ACADEMICS.T_DROPOUT_DETAILS 
		WHERE I_STUDENT_DETAIL_ID = @I_STUDENT_DETAIL_ID
		
		DELETE FROM ACADEMICS.T_DROPOUT_DETAILS 
		WHERE I_STUDENT_DETAIL_ID = @I_STUDENT_DETAIL_ID
		
		--NEW ADD--

		DELETE FROM ACADEMICS.T_DROPOUT_DTLS_AUDIT 
		WHERE I_STUDENT_ID = @I_STUDENT_DETAIL_ID
			
		-- DELETE STUDENT HIERARCHY MAP
		DELETE FROM T_USER_HIERARCHY_DETAILS
		WHERE I_USER_ID IN (	SELECT I_USER_ID
								FROM T_USER_MASTER 
								WHERE I_REFERENCE_ID = @I_STUDENT_DETAIL_ID
								AND S_USER_TYPE = 'ST'	)

		-- DELETE STUDENT ROLE MAP
		DELETE FROM T_USER_ROLE_DETAILS
		WHERE I_USER_ID IN (	SELECT I_USER_ID
								FROM T_USER_MASTER 
								WHERE I_REFERENCE_ID = @I_STUDENT_DETAIL_ID
								AND S_USER_TYPE = 'ST'	)

		DELETE FROM DBO.T_USER_AUDIT_TRAIL
		WHERE I_USER_ID IN (	SELECT I_USER_ID
								FROM T_USER_MASTER 
								WHERE I_REFERENCE_ID = @I_STUDENT_DETAIL_ID
								AND S_USER_TYPE = 'ST'	)
								
		-- DELETE LOGIN TRAIL
		DELETE FROM T_LOGIN_TRAIL
		WHERE I_USER_ID IN (	SELECT I_USER_ID
								FROM T_USER_MASTER 
								WHERE I_REFERENCE_ID = @I_STUDENT_DETAIL_ID
								AND S_USER_TYPE = 'ST'	) 						

		-- DELETE USER DATA
		DELETE FROM T_USER_MASTER
		WHERE I_USER_ID IN (	SELECT I_USER_ID
								FROM T_USER_MASTER 
								WHERE I_REFERENCE_ID = @I_STUDENT_DETAIL_ID
								AND S_USER_TYPE = 'ST'	)

		-- DELETE STUDENT MARKS
		DELETE FROM EXAMINATION.T_STUDENT_MARKS 
		WHERE I_STUDENT_DETAIL_ID = @I_STUDENT_DETAIL_ID

		-- DELETE STUDENT ATTENDANCE
		DELETE FROM T_STUDENT_ATTENDANCE_DETAILS 
		WHERE I_STUDENT_DETAIL_ID = @I_STUDENT_DETAIL_ID


		-- DELETE STUDENT CENTER DETAILS
		DELETE FROM T_STUDENT_CENTER_DETAIL WHERE I_STUDENT_DETAIL_ID = @I_STUDENT_DETAIL_ID

		-- DELETE STUDENT MASTER
		
		DELETE FROM EXAMINATION.T_Eligibility_List WHERE I_STUDENT_DETAIL_ID = @I_STUDENT_DETAIL_ID


		--COMMENTED ABOVE AND ADDED BELOW--
		DELETE FROM T_STUDENT_DETAIL WHERE I_STUDENT_DETAIL_ID = @I_STUDENT_DETAIL_ID
	

COMMIT TRANSACTION
END TRY
BEGIN CATCH
SELECT ERROR_MESSAGE(),ERROR_SEVERITY()
ROLLBACK TRANSACTION
END CATCH
END
