CREATE PROCEDURE [dbo].[uspGetPageName]
(
	@SPAGENAME Nnvarchar(max)
)
AS 

BEGIN

	IF EXISTS(SELECT 'TRUE' FROM T_TRANSACTION_MULTILINGUAL WHERE 'ASP.'+ (CASE WHEN S_MODULE_NAME IS NULL THEN '' ELSE S_MODULE_NAME+'_' END)+REPLACE(S_PAGE_NAME,'.','_')=@SPAGENAME AND I_STATUS=1)
		BEGIN
			SELECT 'Y' AS 'ENABLEMULTILINGUALFEATURES'
		END
	ELSE
		BEGIN
			SELECT 'N' AS 'ENABLEMULTILINGUALFEATURES'
		END
END

