CREATE PROCEDURE [dbo].[uspGetDistinctBatchContents]      
AS       
BEGIN TRY      
 DECLARE @V_DISTINCTBATCHCONTENTS VARCHAR(3000)    
 DECLARE @V_BATCHID VARCHAR(10)    
 SET @V_DISTINCTBATCHCONTENTS =''    
 SET @V_BATCHID =''    
 DECLARE CUR_DISTINCTBATCHCONTENTS CURSOR FOR    
 SELECT DISTINCT I_BATCH_ID FROM T_BATCH_CONTENT_DETAILS WHERE ISNULL(S_CONTENT_URL, '') <> '' ORDER BY 1    
 OPEN CUR_DISTINCTBATCHCONTENTS     
 FETCH NEXT FROM CUR_DISTINCTBATCHCONTENTS INTO @V_BATCHID    
 WHILE @@FETCH_STATUS=0    
 BEGIN    
  SET @V_DISTINCTBATCHCONTENTS  = @V_DISTINCTBATCHCONTENTS  + @V_BATCHID + ','    
  FETCH NEXT FROM CUR_DISTINCTBATCHCONTENTS INTO @V_BATCHID    
 END    
 CLOSE CUR_DISTINCTBATCHCONTENTS     
 DEALLOCATE CUR_DISTINCTBATCHCONTENTS     
 IF (LEN(@V_DISTINCTBATCHCONTENTS) > 0)
 BEGIN
	SET @V_DISTINCTBATCHCONTENTS  = LEFT(@V_DISTINCTBATCHCONTENTS, LEN(@V_DISTINCTBATCHCONTENTS)-1)    
 END
 SELECT @V_DISTINCTBATCHCONTENTS      
END TRY      
BEGIN CATCH      
 DECLARE @ErrMsg NVARCHAR(4000), @ErrSeverity int      
 SELECT @ErrMsg = ERROR_MESSAGE(),      
 @ErrSeverity = ERROR_SEVERITY()      
 RAISERROR(@ErrMsg, @ErrSeverity, 1)      
END CATCH
