CREATE PROCEDURE [dbo].[uspGetDiscountforHierarchDetails] 
(
	@iHierarchyDetailID int,
	@iCenterID int
)

AS
Begin
	Set NoCount On;;

	DECLARE @I_BRAND_ID INT

	Select @I_BRAND_ID=I_BRAND_ID From DBO.T_BRAND_CENTER_DETAILS Where I_CENTRE_ID=@ICENTERID
	IF EXISTS(Select N_DISCOUNT_PERCENTAGE From T_CENTER_DISCOUNT_DETAILS A   
 Where A.I_HIERARCHY_DETAIL_ID = @IHIERARCHYDETAILID AND A.I_CENTER_ID = @ICENTERID AND A.I_BRAND_ID =@I_BRAND_ID AND A.I_STATUS=1)  
  
  Begin   
   Select N_DISCOUNT_PERCENTAGE From T_CENTER_DISCOUNT_DETAILS A   
 Where A.I_HIERARCHY_DETAIL_ID = @IHIERARCHYDETAILID AND A.I_CENTER_ID = @ICENTERID AND A.I_BRAND_ID =@I_BRAND_ID AND A.I_STATUS=1  
  End 
    ELSE IF EXISTS (Select N_DISCOUNT_PERCENTAGE	From T_CENTER_DISCOUNT_DETAILS A 
	Where A.I_HIERARCHY_DETAIL_ID = @IHIERARCHYDETAILID	AND A.I_CENTER_ID = @ICENTERID AND A.I_BRAND_ID IS NULL AND A.I_STATUS=1)

		Begin
			Select N_DISCOUNT_PERCENTAGE From T_CENTER_DISCOUNT_DETAILS A
			Where A.I_HIERARCHY_DETAIL_ID = @IHIERARCHYDETAILID	AND A.I_CENTER_ID = @ICENTERID AND A.I_BRAND_ID IS NULL AND A.I_STATUS=1
		End	

	ELSE IF EXISTS (Select N_DISCOUNT_PERCENTAGE From T_CENTER_DISCOUNT_DETAILS A 
	Where A.I_HIERARCHY_DETAIL_ID = @IHIERARCHYDETAILID	AND A.I_CENTER_ID IS NULL AND A.I_BRAND_ID=@I_BRAND_ID AND A.I_STATUS=1)

		Begin	
			Select N_DISCOUNT_PERCENTAGE From T_CENTER_DISCOUNT_DETAILS A
			Where A.I_HIERARCHY_DETAIL_ID = @IHIERARCHYDETAILID	AND A.I_CENTER_ID IS NULL AND A.I_BRAND_ID=@I_BRAND_ID AND A.I_STATUS=1
		End	

	ELSE IF EXISTS (Select N_DISCOUNT_PERCENTAGE From T_CENTER_DISCOUNT_DETAILS A 
	Where A.I_HIERARCHY_DETAIL_ID = @IHIERARCHYDETAILID	AND A.I_CENTER_ID IS NULL AND A.I_BRAND_ID IS NULL AND A.I_STATUS=1)

		Begin	
			Select N_DISCOUNT_PERCENTAGE From T_CENTER_DISCOUNT_DETAILS A
			Where A.I_HIERARCHY_DETAIL_ID = @IHIERARCHYDETAILID	AND A.I_CENTER_ID IS NULL AND A.I_BRAND_ID IS NULL AND A.I_STATUS=1
		End	
	ELSE
		Begin
			Select 0 AS N_DISCOUNT_PERCENTAGE
		End
End
