CREATE PROC [dbo].[uspGetQueryResult]
(
@sSql VARCHAR(MAX) = null
)

AS 
BEGIN
	SET NOCOUNT ON
	SET XACT_ABORT ON

	BEGIN TRY
		BEGIN TRANSACTION
			DECLARE @sStrSql NVARCHAR(MAX)

			SET @sStrSql = CAST(@sSql as nvarchar(MAX))

			EXEC SP_EXECUTESQL @sStrSql

		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		PRINT ERROR_MESSAGE()
		ROLLBACK TRANSACTION
	END CATCH
END
