CREATE TABLE [NETWORK].[T_Center_Payment_Details_Audit] (
    [I_Center_Pmnt_Details_Audit_ID] INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [I_Payment_ID]                   INT             NULL,
    [I_Centre_Id]                    INT             NULL,
    [I_Payment_Charges_ID]           INT             NULL,
    [I_Payment_Mode]                 INT             NULL,
    [Dt_Payment_Date]                DATETIME        NULL,
    [Dt_Cheque_Date]                 DATETIME        NULL,
    [S_Cheque_Number]                VARCHAR (20)    NULL,
    [S_Bank_Name]                    VARCHAR (20)    NULL,
    [S_CreditCard_No]                VARCHAR (20)    NULL,
    [I_Status]                       INT             NOT NULL,
    [S_Credit_Card_Issuer]           VARCHAR (100)   NULL,
    [S_Credit_Card_Expiry]           VARCHAR (20)    NULL,
    [D_Total_Amount]                 DECIMAL (18, 2) NULL,
    [I_Transfer_To_SAP]              BIT             NULL,
    [Dt_From_Date]                   DATETIME        NULL,
    [Dt_To_Date]                     DATETIME        NULL,
    [Dt_Due_Date]                    DATETIME        NULL,
    [S_Reason]                       VARCHAR (1000)  NULL,
    [S_Remarks]                      VARCHAR (200)   NULL,
    [I_Payment_Type]                 INT             NULL,
    [S_Crtd_By]                      VARCHAR (20)    NULL,
    [S_Upd_By]                       VARCHAR (20)    NULL,
    [Dt_Crtd_On]                     DATETIME        NULL,
    [Dt_Upd_On]                      DATETIME        NULL,
    CONSTRAINT [PK__T_Center_Payment__5E169ED5] PRIMARY KEY CLUSTERED ([I_Center_Pmnt_Details_Audit_ID] ASC)
);

