CREATE TABLE [NETWORK].[T_Ownership_Transfer_Audit] (
    [I_Ownership_Transfer_Audit_ID]  INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [I_Center_Ownership_Transfer_ID] INT            NOT NULL,
    [I_Centre_Id]                    INT            NULL,
    [S_Reason]                       VARCHAR (200)  NULL,
    [S_Remarks]                      VARCHAR (1000) NULL,
    [I_BP_ID]                        INT            NULL,
    [S_Company_Name]                 VARCHAR (100)  NULL,
    [S_BP_Email]                     VARCHAR (50)   NULL,
    [S_Company_Address1]             VARCHAR (100)  NULL,
    [S_Company_Address2]             VARCHAR (100)  NULL,
    [S_Pin_No]                       VARCHAR (10)   NULL,
    [I_Country_ID]                   INT            NULL,
    [I_State_ID]                     INT            NULL,
    [I_City_ID]                      INT            NULL,
    [I_BP_Type]                      INT            NULL,
    [Dt_Agreement_Date]              DATETIME       NULL,
    [Dt_Effective_Agreement_Date]    DATETIME       NULL,
    [Dt_Expiry_Date]                 DATETIME       NULL,
    [S_Territory]                    VARCHAR (50)   NULL,
    [S_Authorised_Courses]           VARCHAR (200)  NULL,
    [S_Firm_Registration_No]         VARCHAR (20)   NULL,
    [S_Authorised_Signatories]       VARCHAR (100)  NULL,
    [I_Signatories_Age]              INT            NULL,
    [S_Signatories_Address1]         VARCHAR (100)  NULL,
    [S_Signatories_Address2]         VARCHAR (100)  NULL,
    [I_Signatories_City]             INT            NULL,
    [I_Signatories_State]            INT            NULL,
    [I_Signatories_Country]          INT            NULL,
    [S_Signatoires_Pin]              VARCHAR (10)   NULL,
    [I_Status]                       INT            NULL,
    [S_Crtd_By]                      VARCHAR (20)   NULL,
    [S_Upd_By]                       VARCHAR (20)   NULL,
    [Dt_Crtd_On]                     DATETIME       NULL,
    [Dt_Upd_On]                      DATETIME       NULL,
    [S_Phone_Number]                 VARCHAR (50)   NULL,
    [S_Signatories_Phone_Number]     VARCHAR (50)   NULL,
    CONSTRAINT [PK__T_Ownership_Tran__4A19C7C9] PRIMARY KEY CLUSTERED ([I_Ownership_Transfer_Audit_ID] ASC)
);

