CREATE TYPE [dbo].[PreEnquiryBulkUploadType] AS TABLE (
    [FirstName]         VARCHAR (50)   NULL,
    [MiddleName]        VARCHAR (50)   NULL,
    [LastName]          VARCHAR (50)   NULL,
    [DateOfBirth]       DATE           NULL,
    [MobileNo]          VARCHAR (20)   NULL,
    [FatherFirstName]   NVARCHAR (100) NULL,
    [FatherMiddleName]  NVARCHAR (100) NULL,
    [FatherLastName]    NVARCHAR (100) NULL,
    [MotherFirstName]   NVARCHAR (100) NULL,
    [MotherMiddleName]  NVARCHAR (100) NULL,
    [MotherLastName]    NVARCHAR (100) NULL,
    [FatherEmailId]     NVARCHAR (100) NULL,
    [MotherEmailId]     NVARCHAR (100) NULL,
    [FatherMobileNo]    NVARCHAR (50)  NULL,
    [MotherMobileNo]    NVARCHAR (50)  NULL,
    [CurrAddress1]      VARCHAR (MAX)  NULL,
    [CurrAddress2]      VARCHAR (MAX)  NULL,
    [CurrCountryId]     INT            NULL,
    [CurrStateId]       INT            NULL,
    [CurrCityId]        INT            NULL,
    [CurrPinCode]       VARCHAR (20)   NULL,
    [PermAddress1]      VARCHAR (MAX)  NULL,
    [PermAddress2]      VARCHAR (MAX)  NULL,
    [PermCountryId]     INT            NULL,
    [PermStateId]       INT            NULL,
    [PermCityId]        INT            NULL,
    [PermPinCode]       VARCHAR (20)   NULL,
    [EnquiryTypeId]     INT            NULL,
    [ClassId]           INT            NULL,
    [StreamId]          INT            NULL,
    [AcademicSessionId] INT            NULL);

