CREATE TYPE [dbo].[UT_ExamScheduleSubjectTableType] AS TABLE (
    [inExamScheduleDetailId] INT             NULL,
    [inClassId]              INT             NULL,
    [inStreamId]             INT             NULL,
    [inSectionId]            INT             NULL,
    [inSubjectTypeID]        INT             NULL,
    [inSubjectID]            INT             NULL,
    [inSubjectComponentID]   INT             NULL,
    [inDisplaySeq]           INT             NULL,
    [inExamMode]             INT             NULL,
    [inExamPlatform]         INT             NULL,
    [dcFullMarks]            DECIMAL (18, 2) NULL,
    [dcMainExamFullMarks]    DECIMAL (18, 2) NULL,
    [dcInternalFullMarks]    DECIMAL (18, 2) NULL,
    [dcOrderallPassMarks]    DECIMAL (18, 2) NULL,
    [isPassMandatory]        BIT             NULL,
    [dtStartDate]            DATETIME        NULL,
    [dtEndDate]              DATETIME        NULL,
    [inExamSlotId]           INT             NULL,
    [isDisplayOnApp]         BIT             NULL,
    [inExamInvigilatorId]    INT             NULL,
    [inExamGraderId]         INT             NULL,
    [inModifiedBy]           INT             NULL);

